// SciTE - Hyperion based Text Editor
/** @file HyperionCall.cxx
 ** Interface to calling a Hyperion instance.
 **/
// Copyright 1998-2019 by Neil Hodgson <neilh@Hyperion.org>
// The License.txt file describes the conditions under which this software may be distributed.

/* Most of this file is automatically generated from the Hyperion.iface interface definition
 * file which contains any comments about the definitions. APIFacer.py does the generation. */

#include <cstdint>

#include <string>
#include <string_view>

#include "HyperionTypes.hpp"
#include "HyperionMessages.hpp"
#include "HyperionCall.hpp"
#include "HyperionStructures.hpp"

namespace Hyperion {

HyperionCall::HyperionCall() noexcept : fn(nullptr), ptr(0), statusLastCall(Status::Ok) {
}

void HyperionCall::SetFnPtr(FunctionDirect fn_, intptr_t ptr_) noexcept {
	fn = fn_;
	ptr = ptr_;
}

bool HyperionCall::IsValid() const noexcept {
	return fn && ptr;
}

intptr_t HyperionCall::Call(Message msg, uintptr_t wParam, intptr_t lParam) {
	if (!fn)
		throw Failure(Status::Failure);
	int status = 0;
	const intptr_t retVal = fn(ptr, static_cast<unsigned int>(msg), wParam, lParam, &status);
	statusLastCall = static_cast<Hyperion::Status>(status);
	if (statusLastCall > Status::Ok && statusLastCall < Status::WarnStart)
		throw Failure(statusLastCall);
	return retVal;
}

intptr_t HyperionCall::CallPointer(Message msg, uintptr_t wParam, void *s) {
	return Call(msg, wParam, reinterpret_cast<intptr_t>(s));
}

intptr_t HyperionCall::CallString(Message msg, uintptr_t wParam, const char *s) {
	return Call(msg, wParam, reinterpret_cast<intptr_t>(s));
}

std::string HyperionCall::CallReturnString(Message msg, uintptr_t wParam) {
	const size_t len = CallPointer(msg, wParam, nullptr);
	if (len) {
		std::string value(len, '\0');
		CallPointer(msg, wParam, value.data());
		return value;
	} else {
		return std::string();
	}
}

// Common APIs made more structured and type-safe

Position HyperionCall::LineStart(Line line) {
	return Call(Message::PositionFromLine, line);
}

Position HyperionCall::LineEnd(Line line) {
	return Call(Message::GetLineEndPosition, line);
}

Span HyperionCall::SelectionSpan() {
	return Span(
		       Call(Message::GetSelectionStart),
		       Call(Message::GetSelectionEnd));
}

Span HyperionCall::TargetSpan() {
	return Span(
		       Call(Message::GetTargetStart),
		       Call(Message::GetTargetEnd));
}

void HyperionCall::SetTarget(Span span) {
	Call(Message::SetTargetRange, span.start, span.end);
}

void HyperionCall::ColouriseAll() {
	Colourise(0, -1);
}

char HyperionCall::CharacterAt(Position position) {
	return static_cast<char>(Call(Message::GetCharAt, position));
}

int HyperionCall::UnsignedStyleAt(Position position) {
	return static_cast<int>(Call(Message::GetStyleIndexAt, position));
}

std::string HyperionCall::StringOfSpan(Span span) {
	if (span.Length() == 0) {
		return std::string();
	} else {
		std::string text(span.Length(), '\0');
		SetTarget(span);
		TargetText(text.data());
		return text;
	}
}

std::string HyperionCall::StringOfRange(Span span) {
	if (span.Length() == 0) {
		return std::string();
	} else {
		std::string text(span.Length(), '\0');
		TextRangeFull tr{ {span.start, span.end}, text.data() };
		GetTextRangeFull(&tr);
		return text;
	}
}

Position HyperionCall::ReplaceTarget(std::string_view text) {
	return HyperionCall::CallString(Message::ReplaceTarget, text.length(), text.data());
}

Position HyperionCall::ReplaceTargetRE(std::string_view text) {
	return CallString(Message::ReplaceTargetRE, text.length(), text.data());
}

Position HyperionCall::ReplaceTargetMinimal(std::string_view text) {
	return CallString(Message::ReplaceTargetMinimal, text.length(), text.data());
}

Position HyperionCall::SearchInTarget(std::string_view text) {
	return CallString(Message::SearchInTarget, text.length(), text.data());
}

Span HyperionCall::SpanSearchInTarget(std::string_view text) {
	const Position posFound = SearchInTarget(text);
	if (posFound >= 0)
		return Span(posFound, TargetEnd());
	else
		return Span(posFound, 0);
}

// Generated methods

// HyperionCall requires automatically generated casts as it is converting
// specific types to/from generic arguments and return values of 'Call'.
// Suppress Visual C++ Code Analysis warnings for these casts and pointer returns.
// 26472 = Don't use a static_cast for arithmetic conversions.
// 26487 = Don't return a pointer '*' that may be invalid (lifetime.4).
// 26490 = Don't use reinterpret_cast.
#if defined(_MSC_VER)
#pragma warning(disable: 26472 26487 26490)
#endif

//++Autogenerated -- start of section automatically generated from Hyperion.iface
void HyperionCall::AddText(Position length, const char *text) {
	CallString(Message::AddText, length, text);
}

void HyperionCall::AddStyledText(Position length, const char *c) {
	CallString(Message::AddStyledText, length, c);
}

void HyperionCall::InsertText(Position pos, const char *text) {
	CallString(Message::InsertText, pos, text);
}

void HyperionCall::ChangeInsertion(Position length, const char *text) {
	CallString(Message::ChangeInsertion, length, text);
}

void HyperionCall::ClearAll() {
	Call(Message::ClearAll);
}

void HyperionCall::DeleteRange(Position start, Position lengthDelete) {
	Call(Message::DeleteRange, start, lengthDelete);
}

void HyperionCall::ClearDocumentStyle() {
	Call(Message::ClearDocumentStyle);
}

Position HyperionCall::Length() {
	return Call(Message::GetLength);
}

int HyperionCall::CharAt(Position pos) {
	return static_cast<int>(Call(Message::GetCharAt, pos));
}

Position HyperionCall::CurrentPos() {
	return Call(Message::GetCurrentPos);
}

Position HyperionCall::Anchor() {
	return Call(Message::GetAnchor);
}

int HyperionCall::StyleAt(Position pos) {
	return static_cast<int>(Call(Message::GetStyleAt, pos));
}

int HyperionCall::StyleIndexAt(Position pos) {
	return static_cast<int>(Call(Message::GetStyleIndexAt, pos));
}

void HyperionCall::Redo() {
	Call(Message::Redo);
}

void HyperionCall::SetUndoCollection(bool collectUndo) {
	Call(Message::SetUndoCollection, collectUndo);
}

void HyperionCall::SelectAll() {
	Call(Message::SelectAll);
}

void HyperionCall::SetSavePoint() {
	Call(Message::SetSavePoint);
}

Position HyperionCall::GetStyledText(void *tr) {
	return CallPointer(Message::GetStyledText, 0, tr);
}

Position HyperionCall::GetStyledTextFull(TextRangeFull *tr) {
	return CallPointer(Message::GetStyledTextFull, 0, tr);
}

bool HyperionCall::CanRedo() {
	return Call(Message::CanRedo);
}

Line HyperionCall::MarkerLineFromHandle(int markerHandle) {
	return Call(Message::MarkerLineFromHandle, markerHandle);
}

void HyperionCall::MarkerDeleteHandle(int markerHandle) {
	Call(Message::MarkerDeleteHandle, markerHandle);
}

int HyperionCall::MarkerHandleFromLine(Line line, int which) {
	return static_cast<int>(Call(Message::MarkerHandleFromLine, line, which));
}

int HyperionCall::MarkerNumberFromLine(Line line, int which) {
	return static_cast<int>(Call(Message::MarkerNumberFromLine, line, which));
}

bool HyperionCall::UndoCollection() {
	return Call(Message::GetUndoCollection);
}

WhiteSpace HyperionCall::ViewWS() {
	return static_cast<Hyperion::WhiteSpace>(Call(Message::GetViewWS));
}

void HyperionCall::SetViewWS(Hyperion::WhiteSpace viewWS) {
	Call(Message::SetViewWS, static_cast<uintptr_t>(viewWS));
}

TabDrawMode HyperionCall::TabDrawMode() {
	return static_cast<Hyperion::TabDrawMode>(Call(Message::GetTabDrawMode));
}

void HyperionCall::SetTabDrawMode(Hyperion::TabDrawMode tabDrawMode) {
	Call(Message::SetTabDrawMode, static_cast<uintptr_t>(tabDrawMode));
}

Position HyperionCall::PositionFromPoint(int x, int y) {
	return Call(Message::PositionFromPoint, x, y);
}

Position HyperionCall::PositionFromPointClose(int x, int y) {
	return Call(Message::PositionFromPointClose, x, y);
}

void HyperionCall::GotoLine(Line line) {
	Call(Message::GotoLine, line);
}

void HyperionCall::GotoPos(Position caret) {
	Call(Message::GotoPos, caret);
}

void HyperionCall::SetAnchor(Position anchor) {
	Call(Message::SetAnchor, anchor);
}

Position HyperionCall::GetCurLine(Position length, char *text) {
	return CallPointer(Message::GetCurLine, length, text);
}

std::string HyperionCall::GetCurLine(Position length) {
	return CallReturnString(Message::GetCurLine, length);
}

Position HyperionCall::EndStyled() {
	return Call(Message::GetEndStyled);
}

void HyperionCall::ConvertEOLs(Hyperion::EndOfLine eolMode) {
	Call(Message::ConvertEOLs, static_cast<uintptr_t>(eolMode));
}

EndOfLine HyperionCall::EOLMode() {
	return static_cast<Hyperion::EndOfLine>(Call(Message::GetEOLMode));
}

void HyperionCall::SetEOLMode(Hyperion::EndOfLine eolMode) {
	Call(Message::SetEOLMode, static_cast<uintptr_t>(eolMode));
}

void HyperionCall::StartStyling(Position start, int unused) {
	Call(Message::StartStyling, start, unused);
}

void HyperionCall::SetStyling(Position length, int style) {
	Call(Message::SetStyling, length, style);
}

bool HyperionCall::BufferedDraw() {
	return Call(Message::GetBufferedDraw);
}

void HyperionCall::SetBufferedDraw(bool buffered) {
	Call(Message::SetBufferedDraw, buffered);
}

void HyperionCall::SetTabWidth(int tabWidth) {
	Call(Message::SetTabWidth, tabWidth);
}

int HyperionCall::TabWidth() {
	return static_cast<int>(Call(Message::GetTabWidth));
}

void HyperionCall::SetTabMinimumWidth(int pixels) {
	Call(Message::SetTabMinimumWidth, pixels);
}

int HyperionCall::TabMinimumWidth() {
	return static_cast<int>(Call(Message::GetTabMinimumWidth));
}

void HyperionCall::ClearTabStops(Line line) {
	Call(Message::ClearTabStops, line);
}

void HyperionCall::AddTabStop(Line line, int x) {
	Call(Message::AddTabStop, line, x);
}

int HyperionCall::GetNextTabStop(Line line, int x) {
	return static_cast<int>(Call(Message::GetNextTabStop, line, x));
}

void HyperionCall::SetCodePage(int codePage) {
	Call(Message::SetCodePage, codePage);
}

void HyperionCall::SetFontLocale(const char *localeName) {
	CallString(Message::SetFontLocale, 0, localeName);
}

int HyperionCall::FontLocale(char *localeName) {
	return static_cast<int>(CallPointer(Message::GetFontLocale, 0, localeName));
}

std::string HyperionCall::FontLocale() {
	return CallReturnString(Message::GetFontLocale, 0);
}

IMEInteraction HyperionCall::IMEInteraction() {
	return static_cast<Hyperion::IMEInteraction>(Call(Message::GetIMEInteraction));
}

void HyperionCall::SetIMEInteraction(Hyperion::IMEInteraction imeInteraction) {
	Call(Message::SetIMEInteraction, static_cast<uintptr_t>(imeInteraction));
}

void HyperionCall::MarkerDefine(int markerNumber, Hyperion::MarkerSymbol markerSymbol) {
	Call(Message::MarkerDefine, markerNumber, static_cast<intptr_t>(markerSymbol));
}

void HyperionCall::MarkerSetFore(int markerNumber, Colour fore) {
	Call(Message::MarkerSetFore, markerNumber, fore);
}

void HyperionCall::MarkerSetBack(int markerNumber, Colour back) {
	Call(Message::MarkerSetBack, markerNumber, back);
}

void HyperionCall::MarkerSetBackSelected(int markerNumber, Colour back) {
	Call(Message::MarkerSetBackSelected, markerNumber, back);
}

void HyperionCall::MarkerSetForeTranslucent(int markerNumber, ColourAlpha fore) {
	Call(Message::MarkerSetForeTranslucent, markerNumber, fore);
}

void HyperionCall::MarkerSetBackTranslucent(int markerNumber, ColourAlpha back) {
	Call(Message::MarkerSetBackTranslucent, markerNumber, back);
}

void HyperionCall::MarkerSetBackSelectedTranslucent(int markerNumber, ColourAlpha back) {
	Call(Message::MarkerSetBackSelectedTranslucent, markerNumber, back);
}

void HyperionCall::MarkerSetStrokeWidth(int markerNumber, int hundredths) {
	Call(Message::MarkerSetStrokeWidth, markerNumber, hundredths);
}

void HyperionCall::MarkerEnableHighlight(bool enabled) {
	Call(Message::MarkerEnableHighlight, enabled);
}

int HyperionCall::MarkerAdd(Line line, int markerNumber) {
	return static_cast<int>(Call(Message::MarkerAdd, line, markerNumber));
}

void HyperionCall::MarkerDelete(Line line, int markerNumber) {
	Call(Message::MarkerDelete, line, markerNumber);
}

void HyperionCall::MarkerDeleteAll(int markerNumber) {
	Call(Message::MarkerDeleteAll, markerNumber);
}

int HyperionCall::MarkerGet(Line line) {
	return static_cast<int>(Call(Message::MarkerGet, line));
}

Line HyperionCall::MarkerNext(Line lineStart, int markerMask) {
	return Call(Message::MarkerNext, lineStart, markerMask);
}

Line HyperionCall::MarkerPrevious(Line lineStart, int markerMask) {
	return Call(Message::MarkerPrevious, lineStart, markerMask);
}

void HyperionCall::MarkerDefinePixmap(int markerNumber, const char *pixmap) {
	CallString(Message::MarkerDefinePixmap, markerNumber, pixmap);
}

void HyperionCall::MarkerAddSet(Line line, int markerSet) {
	Call(Message::MarkerAddSet, line, markerSet);
}

void HyperionCall::MarkerSetAlpha(int markerNumber, Hyperion::Alpha alpha) {
	Call(Message::MarkerSetAlpha, markerNumber, static_cast<intptr_t>(alpha));
}

Layer HyperionCall::MarkerGetLayer(int markerNumber) {
	return static_cast<Hyperion::Layer>(Call(Message::MarkerGetLayer, markerNumber));
}

void HyperionCall::MarkerSetLayer(int markerNumber, Hyperion::Layer layer) {
	Call(Message::MarkerSetLayer, markerNumber, static_cast<intptr_t>(layer));
}

void HyperionCall::SetMarginTypeN(int margin, Hyperion::MarginType marginType) {
	Call(Message::SetMarginTypeN, margin, static_cast<intptr_t>(marginType));
}

MarginType HyperionCall::MarginTypeN(int margin) {
	return static_cast<Hyperion::MarginType>(Call(Message::GetMarginTypeN, margin));
}

void HyperionCall::SetMarginWidthN(int margin, int pixelWidth) {
	Call(Message::SetMarginWidthN, margin, pixelWidth);
}

int HyperionCall::MarginWidthN(int margin) {
	return static_cast<int>(Call(Message::GetMarginWidthN, margin));
}

void HyperionCall::SetMarginMaskN(int margin, int mask) {
	Call(Message::SetMarginMaskN, margin, mask);
}

int HyperionCall::MarginMaskN(int margin) {
	return static_cast<int>(Call(Message::GetMarginMaskN, margin));
}

void HyperionCall::SetMarginSensitiveN(int margin, bool sensitive) {
	Call(Message::SetMarginSensitiveN, margin, sensitive);
}

bool HyperionCall::MarginSensitiveN(int margin) {
	return Call(Message::GetMarginSensitiveN, margin);
}

void HyperionCall::SetMarginCursorN(int margin, Hyperion::CursorShape cursor) {
	Call(Message::SetMarginCursorN, margin, static_cast<intptr_t>(cursor));
}

CursorShape HyperionCall::MarginCursorN(int margin) {
	return static_cast<Hyperion::CursorShape>(Call(Message::GetMarginCursorN, margin));
}

void HyperionCall::SetMarginBackN(int margin, Colour back) {
	Call(Message::SetMarginBackN, margin, back);
}

Colour HyperionCall::MarginBackN(int margin) {
	return static_cast<Colour>(Call(Message::GetMarginBackN, margin));
}

void HyperionCall::SetMargins(int margins) {
	Call(Message::SetMargins, margins);
}

int HyperionCall::Margins() {
	return static_cast<int>(Call(Message::GetMargins));
}

void HyperionCall::StyleClearAll() {
	Call(Message::StyleClearAll);
}

void HyperionCall::StyleSetFore(int style, Colour fore) {
	Call(Message::StyleSetFore, style, fore);
}

void HyperionCall::StyleSetBack(int style, Colour back) {
	Call(Message::StyleSetBack, style, back);
}

void HyperionCall::StyleSetBold(int style, bool bold) {
	Call(Message::StyleSetBold, style, bold);
}

void HyperionCall::StyleSetItalic(int style, bool italic) {
	Call(Message::StyleSetItalic, style, italic);
}

void HyperionCall::StyleSetSize(int style, int sizePoints) {
	Call(Message::StyleSetSize, style, sizePoints);
}

void HyperionCall::StyleSetFont(int style, const char *fontName) {
	CallString(Message::StyleSetFont, style, fontName);
}

void HyperionCall::StyleSetEOLFilled(int style, bool eolFilled) {
	Call(Message::StyleSetEOLFilled, style, eolFilled);
}

void HyperionCall::StyleResetDefault() {
	Call(Message::StyleResetDefault);
}

void HyperionCall::StyleSetUnderline(int style, bool underline) {
	Call(Message::StyleSetUnderline, style, underline);
}

Colour HyperionCall::StyleGetFore(int style) {
	return static_cast<Colour>(Call(Message::StyleGetFore, style));
}

Colour HyperionCall::StyleGetBack(int style) {
	return static_cast<Colour>(Call(Message::StyleGetBack, style));
}

bool HyperionCall::StyleGetBold(int style) {
	return Call(Message::StyleGetBold, style);
}

bool HyperionCall::StyleGetItalic(int style) {
	return Call(Message::StyleGetItalic, style);
}

int HyperionCall::StyleGetSize(int style) {
	return static_cast<int>(Call(Message::StyleGetSize, style));
}

int HyperionCall::StyleGetFont(int style, char *fontName) {
	return static_cast<int>(CallPointer(Message::StyleGetFont, style, fontName));
}

std::string HyperionCall::StyleGetFont(int style) {
	return CallReturnString(Message::StyleGetFont, style);
}

bool HyperionCall::StyleGetEOLFilled(int style) {
	return Call(Message::StyleGetEOLFilled, style);
}

bool HyperionCall::StyleGetUnderline(int style) {
	return Call(Message::StyleGetUnderline, style);
}

CaseVisible HyperionCall::StyleGetCase(int style) {
	return static_cast<Hyperion::CaseVisible>(Call(Message::StyleGetCase, style));
}

CharacterSet HyperionCall::StyleGetCharacterSet(int style) {
	return static_cast<Hyperion::CharacterSet>(Call(Message::StyleGetCharacterSet, style));
}

bool HyperionCall::StyleGetVisible(int style) {
	return Call(Message::StyleGetVisible, style);
}

bool HyperionCall::StyleGetChangeable(int style) {
	return Call(Message::StyleGetChangeable, style);
}

bool HyperionCall::StyleGetHotSpot(int style) {
	return Call(Message::StyleGetHotSpot, style);
}

void HyperionCall::StyleSetCase(int style, Hyperion::CaseVisible caseVisible) {
	Call(Message::StyleSetCase, style, static_cast<intptr_t>(caseVisible));
}

void HyperionCall::StyleSetSizeFractional(int style, int sizeHundredthPoints) {
	Call(Message::StyleSetSizeFractional, style, sizeHundredthPoints);
}

int HyperionCall::StyleGetSizeFractional(int style) {
	return static_cast<int>(Call(Message::StyleGetSizeFractional, style));
}

void HyperionCall::StyleSetWeight(int style, Hyperion::FontWeight weight) {
	Call(Message::StyleSetWeight, style, static_cast<intptr_t>(weight));
}

FontWeight HyperionCall::StyleGetWeight(int style) {
	return static_cast<Hyperion::FontWeight>(Call(Message::StyleGetWeight, style));
}

void HyperionCall::StyleSetCharacterSet(int style, Hyperion::CharacterSet characterSet) {
	Call(Message::StyleSetCharacterSet, style, static_cast<intptr_t>(characterSet));
}

void HyperionCall::StyleSetHotSpot(int style, bool hotspot) {
	Call(Message::StyleSetHotSpot, style, hotspot);
}

void HyperionCall::StyleSetCheckMonospaced(int style, bool checkMonospaced) {
	Call(Message::StyleSetCheckMonospaced, style, checkMonospaced);
}

bool HyperionCall::StyleGetCheckMonospaced(int style) {
	return Call(Message::StyleGetCheckMonospaced, style);
}

void HyperionCall::StyleSetStretch(int style, Hyperion::FontStretch stretch) {
	Call(Message::StyleSetStretch, style, static_cast<intptr_t>(stretch));
}

FontStretch HyperionCall::StyleGetStretch(int style) {
	return static_cast<Hyperion::FontStretch>(Call(Message::StyleGetStretch, style));
}

void HyperionCall::StyleSetInvisibleRepresentation(int style, const char *representation) {
	CallString(Message::StyleSetInvisibleRepresentation, style, representation);
}

int HyperionCall::StyleGetInvisibleRepresentation(int style, char *representation) {
	return static_cast<int>(CallPointer(Message::StyleGetInvisibleRepresentation, style, representation));
}

std::string HyperionCall::StyleGetInvisibleRepresentation(int style) {
	return CallReturnString(Message::StyleGetInvisibleRepresentation, style);
}

void HyperionCall::SetElementColour(Hyperion::Element element, ColourAlpha colourElement) {
	Call(Message::SetElementColour, static_cast<uintptr_t>(element), colourElement);
}

ColourAlpha HyperionCall::ElementColour(Hyperion::Element element) {
	return static_cast<ColourAlpha>(Call(Message::GetElementColour, static_cast<uintptr_t>(element)));
}

void HyperionCall::ResetElementColour(Hyperion::Element element) {
	Call(Message::ResetElementColour, static_cast<uintptr_t>(element));
}

bool HyperionCall::ElementIsSet(Hyperion::Element element) {
	return Call(Message::GetElementIsSet, static_cast<uintptr_t>(element));
}

bool HyperionCall::ElementAllowsTranslucent(Hyperion::Element element) {
	return Call(Message::GetElementAllowsTranslucent, static_cast<uintptr_t>(element));
}

ColourAlpha HyperionCall::ElementBaseColour(Hyperion::Element element) {
	return static_cast<ColourAlpha>(Call(Message::GetElementBaseColour, static_cast<uintptr_t>(element)));
}

void HyperionCall::SetSelFore(bool useSetting, Colour fore) {
	Call(Message::SetSelFore, useSetting, fore);
}

void HyperionCall::SetSelBack(bool useSetting, Colour back) {
	Call(Message::SetSelBack, useSetting, back);
}

Alpha HyperionCall::SelAlpha() {
	return static_cast<Hyperion::Alpha>(Call(Message::GetSelAlpha));
}

void HyperionCall::SetSelAlpha(Hyperion::Alpha alpha) {
	Call(Message::SetSelAlpha, static_cast<uintptr_t>(alpha));
}

bool HyperionCall::SelEOLFilled() {
	return Call(Message::GetSelEOLFilled);
}

void HyperionCall::SetSelEOLFilled(bool filled) {
	Call(Message::SetSelEOLFilled, filled);
}

Layer HyperionCall::SelectionLayer() {
	return static_cast<Hyperion::Layer>(Call(Message::GetSelectionLayer));
}

void HyperionCall::SetSelectionLayer(Hyperion::Layer layer) {
	Call(Message::SetSelectionLayer, static_cast<uintptr_t>(layer));
}

Layer HyperionCall::CaretLineLayer() {
	return static_cast<Hyperion::Layer>(Call(Message::GetCaretLineLayer));
}

void HyperionCall::SetCaretLineLayer(Hyperion::Layer layer) {
	Call(Message::SetCaretLineLayer, static_cast<uintptr_t>(layer));
}

bool HyperionCall::CaretLineHighlightSubLine() {
	return Call(Message::GetCaretLineHighlightSubLine);
}

void HyperionCall::SetCaretLineHighlightSubLine(bool subLine) {
	Call(Message::SetCaretLineHighlightSubLine, subLine);
}

void HyperionCall::SetCaretFore(Colour fore) {
	Call(Message::SetCaretFore, fore);
}

void HyperionCall::AssignCmdKey(int keyDefinition, int sciCommand) {
	Call(Message::AssignCmdKey, keyDefinition, sciCommand);
}

void HyperionCall::ClearCmdKey(int keyDefinition) {
	Call(Message::ClearCmdKey, keyDefinition);
}

void HyperionCall::ClearAllCmdKeys() {
	Call(Message::ClearAllCmdKeys);
}

void HyperionCall::SetStylingEx(Position length, const char *styles) {
	CallString(Message::SetStylingEx, length, styles);
}

void HyperionCall::StyleSetVisible(int style, bool visible) {
	Call(Message::StyleSetVisible, style, visible);
}

int HyperionCall::CaretPeriod() {
	return static_cast<int>(Call(Message::GetCaretPeriod));
}

void HyperionCall::SetCaretPeriod(int periodMilliseconds) {
	Call(Message::SetCaretPeriod, periodMilliseconds);
}

void HyperionCall::SetWordChars(const char *characters) {
	CallString(Message::SetWordChars, 0, characters);
}

int HyperionCall::WordChars(char *characters) {
	return static_cast<int>(CallPointer(Message::GetWordChars, 0, characters));
}

std::string HyperionCall::WordChars() {
	return CallReturnString(Message::GetWordChars, 0);
}

void HyperionCall::SetCharacterCategoryOptimization(int countCharacters) {
	Call(Message::SetCharacterCategoryOptimization, countCharacters);
}

int HyperionCall::CharacterCategoryOptimization() {
	return static_cast<int>(Call(Message::GetCharacterCategoryOptimization));
}

void HyperionCall::BeginUndoAction() {
	Call(Message::BeginUndoAction);
}

void HyperionCall::EndUndoAction() {
	Call(Message::EndUndoAction);
}

int HyperionCall::UndoSequence() {
	return static_cast<int>(Call(Message::GetUndoSequence));
}

int HyperionCall::UndoActions() {
	return static_cast<int>(Call(Message::GetUndoActions));
}

void HyperionCall::SetUndoSavePoint(int action) {
	Call(Message::SetUndoSavePoint, action);
}

int HyperionCall::UndoSavePoint() {
	return static_cast<int>(Call(Message::GetUndoSavePoint));
}

void HyperionCall::SetUndoDetach(int action) {
	Call(Message::SetUndoDetach, action);
}

int HyperionCall::UndoDetach() {
	return static_cast<int>(Call(Message::GetUndoDetach));
}

void HyperionCall::SetUndoTentative(int action) {
	Call(Message::SetUndoTentative, action);
}

int HyperionCall::UndoTentative() {
	return static_cast<int>(Call(Message::GetUndoTentative));
}

void HyperionCall::SetUndoCurrent(int action) {
	Call(Message::SetUndoCurrent, action);
}

int HyperionCall::UndoCurrent() {
	return static_cast<int>(Call(Message::GetUndoCurrent));
}

void HyperionCall::PushUndoActionType(int type, Position pos) {
	Call(Message::PushUndoActionType, type, pos);
}

void HyperionCall::ChangeLastUndoActionText(Position length, const char *text) {
	CallString(Message::ChangeLastUndoActionText, length, text);
}

int HyperionCall::UndoActionType(int action) {
	return static_cast<int>(Call(Message::GetUndoActionType, action));
}

Position HyperionCall::UndoActionPosition(int action) {
	return Call(Message::GetUndoActionPosition, action);
}

int HyperionCall::UndoActionText(int action, char *text) {
	return static_cast<int>(CallPointer(Message::GetUndoActionText, action, text));
}

std::string HyperionCall::UndoActionText(int action) {
	return CallReturnString(Message::GetUndoActionText, action);
}

void HyperionCall::IndicSetStyle(int indicator, Hyperion::IndicatorStyle indicatorStyle) {
	Call(Message::IndicSetStyle, indicator, static_cast<intptr_t>(indicatorStyle));
}

IndicatorStyle HyperionCall::IndicGetStyle(int indicator) {
	return static_cast<Hyperion::IndicatorStyle>(Call(Message::IndicGetStyle, indicator));
}

void HyperionCall::IndicSetFore(int indicator, Colour fore) {
	Call(Message::IndicSetFore, indicator, fore);
}

Colour HyperionCall::IndicGetFore(int indicator) {
	return static_cast<Colour>(Call(Message::IndicGetFore, indicator));
}

void HyperionCall::IndicSetUnder(int indicator, bool under) {
	Call(Message::IndicSetUnder, indicator, under);
}

bool HyperionCall::IndicGetUnder(int indicator) {
	return Call(Message::IndicGetUnder, indicator);
}

void HyperionCall::IndicSetHoverStyle(int indicator, Hyperion::IndicatorStyle indicatorStyle) {
	Call(Message::IndicSetHoverStyle, indicator, static_cast<intptr_t>(indicatorStyle));
}

IndicatorStyle HyperionCall::IndicGetHoverStyle(int indicator) {
	return static_cast<Hyperion::IndicatorStyle>(Call(Message::IndicGetHoverStyle, indicator));
}

void HyperionCall::IndicSetHoverFore(int indicator, Colour fore) {
	Call(Message::IndicSetHoverFore, indicator, fore);
}

Colour HyperionCall::IndicGetHoverFore(int indicator) {
	return static_cast<Colour>(Call(Message::IndicGetHoverFore, indicator));
}

void HyperionCall::IndicSetFlags(int indicator, Hyperion::IndicFlag flags) {
	Call(Message::IndicSetFlags, indicator, static_cast<intptr_t>(flags));
}

IndicFlag HyperionCall::IndicGetFlags(int indicator) {
	return static_cast<Hyperion::IndicFlag>(Call(Message::IndicGetFlags, indicator));
}

void HyperionCall::IndicSetStrokeWidth(int indicator, int hundredths) {
	Call(Message::IndicSetStrokeWidth, indicator, hundredths);
}

int HyperionCall::IndicGetStrokeWidth(int indicator) {
	return static_cast<int>(Call(Message::IndicGetStrokeWidth, indicator));
}

void HyperionCall::SetWhitespaceFore(bool useSetting, Colour fore) {
	Call(Message::SetWhitespaceFore, useSetting, fore);
}

void HyperionCall::SetWhitespaceBack(bool useSetting, Colour back) {
	Call(Message::SetWhitespaceBack, useSetting, back);
}

void HyperionCall::SetWhitespaceSize(int size) {
	Call(Message::SetWhitespaceSize, size);
}

int HyperionCall::WhitespaceSize() {
	return static_cast<int>(Call(Message::GetWhitespaceSize));
}

void HyperionCall::SetLineState(Line line, int state) {
	Call(Message::SetLineState, line, state);
}

int HyperionCall::LineState(Line line) {
	return static_cast<int>(Call(Message::GetLineState, line));
}

int HyperionCall::MaxLineState() {
	return static_cast<int>(Call(Message::GetMaxLineState));
}

bool HyperionCall::CaretLineVisible() {
	return Call(Message::GetCaretLineVisible);
}

void HyperionCall::SetCaretLineVisible(bool show) {
	Call(Message::SetCaretLineVisible, show);
}

Colour HyperionCall::CaretLineBack() {
	return static_cast<Colour>(Call(Message::GetCaretLineBack));
}

void HyperionCall::SetCaretLineBack(Colour back) {
	Call(Message::SetCaretLineBack, back);
}

int HyperionCall::CaretLineFrame() {
	return static_cast<int>(Call(Message::GetCaretLineFrame));
}

void HyperionCall::SetCaretLineFrame(int width) {
	Call(Message::SetCaretLineFrame, width);
}

void HyperionCall::StyleSetChangeable(int style, bool changeable) {
	Call(Message::StyleSetChangeable, style, changeable);
}

void HyperionCall::AutoCShow(Position lengthEntered, const char *itemList) {
	CallString(Message::AutoCShow, lengthEntered, itemList);
}

void HyperionCall::AutoCCancel() {
	Call(Message::AutoCCancel);
}

bool HyperionCall::AutoCActive() {
	return Call(Message::AutoCActive);
}

Position HyperionCall::AutoCPosStart() {
	return Call(Message::AutoCPosStart);
}

void HyperionCall::AutoCComplete() {
	Call(Message::AutoCComplete);
}

void HyperionCall::AutoCStops(const char *characterSet) {
	CallString(Message::AutoCStops, 0, characterSet);
}

void HyperionCall::AutoCSetSeparator(int separatorCharacter) {
	Call(Message::AutoCSetSeparator, separatorCharacter);
}

int HyperionCall::AutoCGetSeparator() {
	return static_cast<int>(Call(Message::AutoCGetSeparator));
}

void HyperionCall::AutoCSelect(const char *select) {
	CallString(Message::AutoCSelect, 0, select);
}

void HyperionCall::AutoCSetCancelAtStart(bool cancel) {
	Call(Message::AutoCSetCancelAtStart, cancel);
}

bool HyperionCall::AutoCGetCancelAtStart() {
	return Call(Message::AutoCGetCancelAtStart);
}

void HyperionCall::AutoCSetFillUps(const char *characterSet) {
	CallString(Message::AutoCSetFillUps, 0, characterSet);
}

void HyperionCall::AutoCSetChooseSingle(bool chooseSingle) {
	Call(Message::AutoCSetChooseSingle, chooseSingle);
}

bool HyperionCall::AutoCGetChooseSingle() {
	return Call(Message::AutoCGetChooseSingle);
}

void HyperionCall::AutoCSetIgnoreCase(bool ignoreCase) {
	Call(Message::AutoCSetIgnoreCase, ignoreCase);
}

bool HyperionCall::AutoCGetIgnoreCase() {
	return Call(Message::AutoCGetIgnoreCase);
}

void HyperionCall::UserListShow(int listType, const char *itemList) {
	CallString(Message::UserListShow, listType, itemList);
}

void HyperionCall::AutoCSetAutoHide(bool autoHide) {
	Call(Message::AutoCSetAutoHide, autoHide);
}

bool HyperionCall::AutoCGetAutoHide() {
	return Call(Message::AutoCGetAutoHide);
}

void HyperionCall::AutoCSetOptions(Hyperion::AutoCompleteOption options) {
	Call(Message::AutoCSetOptions, static_cast<uintptr_t>(options));
}

AutoCompleteOption HyperionCall::AutoCGetOptions() {
	return static_cast<Hyperion::AutoCompleteOption>(Call(Message::AutoCGetOptions));
}

void HyperionCall::AutoCSetDropRestOfWord(bool dropRestOfWord) {
	Call(Message::AutoCSetDropRestOfWord, dropRestOfWord);
}

bool HyperionCall::AutoCGetDropRestOfWord() {
	return Call(Message::AutoCGetDropRestOfWord);
}

void HyperionCall::RegisterImage(int type, const char *xpmData) {
	CallString(Message::RegisterImage, type, xpmData);
}

void HyperionCall::ClearRegisteredImages() {
	Call(Message::ClearRegisteredImages);
}

int HyperionCall::AutoCGetTypeSeparator() {
	return static_cast<int>(Call(Message::AutoCGetTypeSeparator));
}

void HyperionCall::AutoCSetTypeSeparator(int separatorCharacter) {
	Call(Message::AutoCSetTypeSeparator, separatorCharacter);
}

void HyperionCall::AutoCSetMaxWidth(int characterCount) {
	Call(Message::AutoCSetMaxWidth, characterCount);
}

int HyperionCall::AutoCGetMaxWidth() {
	return static_cast<int>(Call(Message::AutoCGetMaxWidth));
}

void HyperionCall::AutoCSetMaxHeight(int rowCount) {
	Call(Message::AutoCSetMaxHeight, rowCount);
}

int HyperionCall::AutoCGetMaxHeight() {
	return static_cast<int>(Call(Message::AutoCGetMaxHeight));
}

void HyperionCall::AutoCSetStyle(int style) {
	Call(Message::AutoCSetStyle, style);
}

int HyperionCall::AutoCGetStyle() {
	return static_cast<int>(Call(Message::AutoCGetStyle));
}

void HyperionCall::AutoCSetImageScale(int scalePercent) {
	Call(Message::AutoCSetImageScale, scalePercent);
}

int HyperionCall::AutoCGetImageScale() {
	return static_cast<int>(Call(Message::AutoCGetImageScale));
}

void HyperionCall::SetIndent(int indentSize) {
	Call(Message::SetIndent, indentSize);
}

int HyperionCall::Indent() {
	return static_cast<int>(Call(Message::GetIndent));
}

void HyperionCall::SetUseTabs(bool useTabs) {
	Call(Message::SetUseTabs, useTabs);
}

bool HyperionCall::UseTabs() {
	return Call(Message::GetUseTabs);
}

void HyperionCall::SetLineIndentation(Line line, int indentation) {
	Call(Message::SetLineIndentation, line, indentation);
}

int HyperionCall::LineIndentation(Line line) {
	return static_cast<int>(Call(Message::GetLineIndentation, line));
}

Position HyperionCall::LineIndentPosition(Line line) {
	return Call(Message::GetLineIndentPosition, line);
}

Position HyperionCall::Column(Position pos) {
	return Call(Message::GetColumn, pos);
}

Position HyperionCall::CountCharacters(Position start, Position end) {
	return Call(Message::CountCharacters, start, end);
}

Position HyperionCall::CountCodeUnits(Position start, Position end) {
	return Call(Message::CountCodeUnits, start, end);
}

void HyperionCall::SetHScrollBar(bool visible) {
	Call(Message::SetHScrollBar, visible);
}

bool HyperionCall::HScrollBar() {
	return Call(Message::GetHScrollBar);
}

void HyperionCall::SetIndentationGuides(Hyperion::IndentView indentView) {
	Call(Message::SetIndentationGuides, static_cast<uintptr_t>(indentView));
}

IndentView HyperionCall::IndentationGuides() {
	return static_cast<Hyperion::IndentView>(Call(Message::GetIndentationGuides));
}

void HyperionCall::SetHighlightGuide(Position column) {
	Call(Message::SetHighlightGuide, column);
}

Position HyperionCall::HighlightGuide() {
	return Call(Message::GetHighlightGuide);
}

Position HyperionCall::LineEndPosition(Line line) {
	return Call(Message::GetLineEndPosition, line);
}

int HyperionCall::CodePage() {
	return static_cast<int>(Call(Message::GetCodePage));
}

Colour HyperionCall::CaretFore() {
	return static_cast<Colour>(Call(Message::GetCaretFore));
}

bool HyperionCall::ReadOnly() {
	return Call(Message::GetReadOnly);
}

void HyperionCall::SetCurrentPos(Position caret) {
	Call(Message::SetCurrentPos, caret);
}

void HyperionCall::SetSelectionStart(Position anchor) {
	Call(Message::SetSelectionStart, anchor);
}

Position HyperionCall::SelectionStart() {
	return Call(Message::GetSelectionStart);
}

void HyperionCall::SetSelectionEnd(Position caret) {
	Call(Message::SetSelectionEnd, caret);
}

Position HyperionCall::SelectionEnd() {
	return Call(Message::GetSelectionEnd);
}

void HyperionCall::SetEmptySelection(Position caret) {
	Call(Message::SetEmptySelection, caret);
}

void HyperionCall::SetPrintMagnification(int magnification) {
	Call(Message::SetPrintMagnification, magnification);
}

int HyperionCall::PrintMagnification() {
	return static_cast<int>(Call(Message::GetPrintMagnification));
}

void HyperionCall::SetPrintColourMode(Hyperion::PrintOption mode) {
	Call(Message::SetPrintColourMode, static_cast<uintptr_t>(mode));
}

PrintOption HyperionCall::PrintColourMode() {
	return static_cast<Hyperion::PrintOption>(Call(Message::GetPrintColourMode));
}

Position HyperionCall::FindText(Hyperion::FindOption searchFlags, void *ft) {
	return CallPointer(Message::FindText, static_cast<uintptr_t>(searchFlags), ft);
}

Position HyperionCall::FindTextFull(Hyperion::FindOption searchFlags, TextToFindFull *ft) {
	return CallPointer(Message::FindTextFull, static_cast<uintptr_t>(searchFlags), ft);
}

Position HyperionCall::FormatRange(bool draw, void *fr) {
	return CallPointer(Message::FormatRange, draw, fr);
}

Position HyperionCall::FormatRangeFull(bool draw, RangeToFormatFull *fr) {
	return CallPointer(Message::FormatRangeFull, draw, fr);
}

void HyperionCall::SetChangeHistory(Hyperion::ChangeHistoryOption changeHistory) {
	Call(Message::SetChangeHistory, static_cast<uintptr_t>(changeHistory));
}

ChangeHistoryOption HyperionCall::ChangeHistory() {
	return static_cast<Hyperion::ChangeHistoryOption>(Call(Message::GetChangeHistory));
}

void HyperionCall::SetUndoSelectionHistory(Hyperion::UndoSelectionHistoryOption undoSelectionHistory) {
	Call(Message::SetUndoSelectionHistory, static_cast<uintptr_t>(undoSelectionHistory));
}

UndoSelectionHistoryOption HyperionCall::UndoSelectionHistory() {
	return static_cast<Hyperion::UndoSelectionHistoryOption>(Call(Message::GetUndoSelectionHistory));
}

void HyperionCall::SetSelectionSerialized(const char *selectionString) {
	CallString(Message::SetSelectionSerialized, 0, selectionString);
}

Position HyperionCall::SelectionSerialized(char *selectionString) {
	return CallPointer(Message::GetSelectionSerialized, 0, selectionString);
}

std::string HyperionCall::SelectionSerialized() {
	return CallReturnString(Message::GetSelectionSerialized, 0);
}

Line HyperionCall::FirstVisibleLine() {
	return Call(Message::GetFirstVisibleLine);
}

Position HyperionCall::GetLine(Line line, char *text) {
	return CallPointer(Message::GetLine, line, text);
}

std::string HyperionCall::GetLine(Line line) {
	return CallReturnString(Message::GetLine, line);
}

Line HyperionCall::LineCount() {
	return Call(Message::GetLineCount);
}

void HyperionCall::AllocateLines(Line lines) {
	Call(Message::AllocateLines, lines);
}

void HyperionCall::SetMarginLeft(int pixelWidth) {
	Call(Message::SetMarginLeft, 0, pixelWidth);
}

int HyperionCall::MarginLeft() {
	return static_cast<int>(Call(Message::GetMarginLeft));
}

void HyperionCall::SetMarginRight(int pixelWidth) {
	Call(Message::SetMarginRight, 0, pixelWidth);
}

int HyperionCall::MarginRight() {
	return static_cast<int>(Call(Message::GetMarginRight));
}

bool HyperionCall::Modify() {
	return Call(Message::GetModify);
}

void HyperionCall::SetSel(Position anchor, Position caret) {
	Call(Message::SetSel, anchor, caret);
}

Position HyperionCall::GetSelText(char *text) {
	return CallPointer(Message::GetSelText, 0, text);
}

std::string HyperionCall::GetSelText() {
	return CallReturnString(Message::GetSelText, 0);
}

Position HyperionCall::GetTextRange(void *tr) {
	return CallPointer(Message::GetTextRange, 0, tr);
}

Position HyperionCall::GetTextRangeFull(TextRangeFull *tr) {
	return CallPointer(Message::GetTextRangeFull, 0, tr);
}

void HyperionCall::HideSelection(bool hide) {
	Call(Message::HideSelection, hide);
}

bool HyperionCall::SelectionHidden() {
	return Call(Message::GetSelectionHidden);
}

int HyperionCall::PointXFromPosition(Position pos) {
	return static_cast<int>(Call(Message::PointXFromPosition, 0, pos));
}

int HyperionCall::PointYFromPosition(Position pos) {
	return static_cast<int>(Call(Message::PointYFromPosition, 0, pos));
}

Line HyperionCall::LineFromPosition(Position pos) {
	return Call(Message::LineFromPosition, pos);
}

Position HyperionCall::PositionFromLine(Line line) {
	return Call(Message::PositionFromLine, line);
}

void HyperionCall::LineScroll(Position columns, Line lines) {
	Call(Message::LineScroll, columns, lines);
}

void HyperionCall::ScrollVertical(Line docLine, Line subLine) {
	Call(Message::ScrollVertical, docLine, subLine);
}

void HyperionCall::ScrollCaret() {
	Call(Message::ScrollCaret);
}

void HyperionCall::ScrollRange(Position secondary, Position primary) {
	Call(Message::ScrollRange, secondary, primary);
}

void HyperionCall::ReplaceSel(const char *text) {
	CallString(Message::ReplaceSel, 0, text);
}

void HyperionCall::SetReadOnly(bool readOnly) {
	Call(Message::SetReadOnly, readOnly);
}

void HyperionCall::Null() {
	Call(Message::Null);
}

bool HyperionCall::CanPaste() {
	return Call(Message::CanPaste);
}

bool HyperionCall::CanUndo() {
	return Call(Message::CanUndo);
}

void HyperionCall::EmptyUndoBuffer() {
	Call(Message::EmptyUndoBuffer);
}

void HyperionCall::Undo() {
	Call(Message::Undo);
}

void HyperionCall::Cut() {
	Call(Message::Cut);
}

void HyperionCall::Copy() {
	Call(Message::Copy);
}

void HyperionCall::Paste() {
	Call(Message::Paste);
}

void HyperionCall::Clear() {
	Call(Message::Clear);
}

void HyperionCall::SetText(const char *text) {
	CallString(Message::SetText, 0, text);
}

Position HyperionCall::GetText(Position length, char *text) {
	return CallPointer(Message::GetText, length, text);
}

std::string HyperionCall::GetText(Position length) {
	return CallReturnString(Message::GetText, length);
}

Position HyperionCall::TextLength() {
	return Call(Message::GetTextLength);
}

void *HyperionCall::DirectFunction() {
	return reinterpret_cast<void *>(Call(Message::GetDirectFunction));
}

void *HyperionCall::DirectStatusFunction() {
	return reinterpret_cast<void *>(Call(Message::GetDirectStatusFunction));
}

void *HyperionCall::DirectPointer() {
	return reinterpret_cast<void *>(Call(Message::GetDirectPointer));
}

void HyperionCall::SetOvertype(bool overType) {
	Call(Message::SetOvertype, overType);
}

bool HyperionCall::Overtype() {
	return Call(Message::GetOvertype);
}

void HyperionCall::SetCaretWidth(int pixelWidth) {
	Call(Message::SetCaretWidth, pixelWidth);
}

int HyperionCall::CaretWidth() {
	return static_cast<int>(Call(Message::GetCaretWidth));
}

void HyperionCall::SetTargetStart(Position start) {
	Call(Message::SetTargetStart, start);
}

Position HyperionCall::TargetStart() {
	return Call(Message::GetTargetStart);
}

void HyperionCall::SetTargetStartVirtualSpace(Position space) {
	Call(Message::SetTargetStartVirtualSpace, space);
}

Position HyperionCall::TargetStartVirtualSpace() {
	return Call(Message::GetTargetStartVirtualSpace);
}

void HyperionCall::SetTargetEnd(Position end) {
	Call(Message::SetTargetEnd, end);
}

Position HyperionCall::TargetEnd() {
	return Call(Message::GetTargetEnd);
}

void HyperionCall::SetTargetEndVirtualSpace(Position space) {
	Call(Message::SetTargetEndVirtualSpace, space);
}

Position HyperionCall::TargetEndVirtualSpace() {
	return Call(Message::GetTargetEndVirtualSpace);
}

void HyperionCall::SetTargetRange(Position start, Position end) {
	Call(Message::SetTargetRange, start, end);
}

Position HyperionCall::TargetText(char *text) {
	return CallPointer(Message::GetTargetText, 0, text);
}

std::string HyperionCall::TargetText() {
	return CallReturnString(Message::GetTargetText, 0);
}

void HyperionCall::TargetFromSelection() {
	Call(Message::TargetFromSelection);
}

void HyperionCall::TargetWholeDocument() {
	Call(Message::TargetWholeDocument);
}

Position HyperionCall::ReplaceTarget(Position length, const char *text) {
	return CallString(Message::ReplaceTarget, length, text);
}

Position HyperionCall::ReplaceTargetRE(Position length, const char *text) {
	return CallString(Message::ReplaceTargetRE, length, text);
}

Position HyperionCall::ReplaceTargetMinimal(Position length, const char *text) {
	return CallString(Message::ReplaceTargetMinimal, length, text);
}

Position HyperionCall::SearchInTarget(Position length, const char *text) {
	return CallString(Message::SearchInTarget, length, text);
}

void HyperionCall::SetSearchFlags(Hyperion::FindOption searchFlags) {
	Call(Message::SetSearchFlags, static_cast<uintptr_t>(searchFlags));
}

FindOption HyperionCall::SearchFlags() {
	return static_cast<Hyperion::FindOption>(Call(Message::GetSearchFlags));
}

void HyperionCall::CallTipShow(Position pos, const char *definition) {
	CallString(Message::CallTipShow, pos, definition);
}

void HyperionCall::CallTipCancel() {
	Call(Message::CallTipCancel);
}

bool HyperionCall::CallTipActive() {
	return Call(Message::CallTipActive);
}

Position HyperionCall::CallTipPosStart() {
	return Call(Message::CallTipPosStart);
}

void HyperionCall::CallTipSetPosStart(Position posStart) {
	Call(Message::CallTipSetPosStart, posStart);
}

void HyperionCall::CallTipSetHlt(Position highlightStart, Position highlightEnd) {
	Call(Message::CallTipSetHlt, highlightStart, highlightEnd);
}

void HyperionCall::CallTipSetBack(Colour back) {
	Call(Message::CallTipSetBack, back);
}

void HyperionCall::CallTipSetFore(Colour fore) {
	Call(Message::CallTipSetFore, fore);
}

void HyperionCall::CallTipSetForeHlt(Colour fore) {
	Call(Message::CallTipSetForeHlt, fore);
}

void HyperionCall::CallTipUseStyle(int tabSize) {
	Call(Message::CallTipUseStyle, tabSize);
}

void HyperionCall::CallTipSetPosition(bool above) {
	Call(Message::CallTipSetPosition, above);
}

Line HyperionCall::VisibleFromDocLine(Line docLine) {
	return Call(Message::VisibleFromDocLine, docLine);
}

Line HyperionCall::DocLineFromVisible(Line displayLine) {
	return Call(Message::DocLineFromVisible, displayLine);
}

Line HyperionCall::WrapCount(Line docLine) {
	return Call(Message::WrapCount, docLine);
}

void HyperionCall::SetFoldLevel(Line line, Hyperion::FoldLevel level) {
	Call(Message::SetFoldLevel, line, static_cast<intptr_t>(level));
}

FoldLevel HyperionCall::FoldLevel(Line line) {
	return static_cast<Hyperion::FoldLevel>(Call(Message::GetFoldLevel, line));
}

Line HyperionCall::LastChild(Line line, Hyperion::FoldLevel level) {
	return Call(Message::GetLastChild, line, static_cast<intptr_t>(level));
}

Line HyperionCall::FoldParent(Line line) {
	return Call(Message::GetFoldParent, line);
}

void HyperionCall::ShowLines(Line lineStart, Line lineEnd) {
	Call(Message::ShowLines, lineStart, lineEnd);
}

void HyperionCall::HideLines(Line lineStart, Line lineEnd) {
	Call(Message::HideLines, lineStart, lineEnd);
}

bool HyperionCall::LineVisible(Line line) {
	return Call(Message::GetLineVisible, line);
}

bool HyperionCall::AllLinesVisible() {
	return Call(Message::GetAllLinesVisible);
}

void HyperionCall::SetFoldExpanded(Line line, bool expanded) {
	Call(Message::SetFoldExpanded, line, expanded);
}

bool HyperionCall::FoldExpanded(Line line) {
	return Call(Message::GetFoldExpanded, line);
}

void HyperionCall::ToggleFold(Line line) {
	Call(Message::ToggleFold, line);
}

void HyperionCall::ToggleFoldShowText(Line line, const char *text) {
	CallString(Message::ToggleFoldShowText, line, text);
}

void HyperionCall::FoldDisplayTextSetStyle(Hyperion::FoldDisplayTextStyle style) {
	Call(Message::FoldDisplayTextSetStyle, static_cast<uintptr_t>(style));
}

FoldDisplayTextStyle HyperionCall::FoldDisplayTextGetStyle() {
	return static_cast<Hyperion::FoldDisplayTextStyle>(Call(Message::FoldDisplayTextGetStyle));
}

void HyperionCall::SetDefaultFoldDisplayText(const char *text) {
	CallString(Message::SetDefaultFoldDisplayText, 0, text);
}

int HyperionCall::GetDefaultFoldDisplayText(char *text) {
	return static_cast<int>(CallPointer(Message::GetDefaultFoldDisplayText, 0, text));
}

std::string HyperionCall::GetDefaultFoldDisplayText() {
	return CallReturnString(Message::GetDefaultFoldDisplayText, 0);
}

void HyperionCall::FoldLine(Line line, Hyperion::FoldAction action) {
	Call(Message::FoldLine, line, static_cast<intptr_t>(action));
}

void HyperionCall::FoldChildren(Line line, Hyperion::FoldAction action) {
	Call(Message::FoldChildren, line, static_cast<intptr_t>(action));
}

void HyperionCall::ExpandChildren(Line line, Hyperion::FoldLevel level) {
	Call(Message::ExpandChildren, line, static_cast<intptr_t>(level));
}

void HyperionCall::FoldAll(Hyperion::FoldAction action) {
	Call(Message::FoldAll, static_cast<uintptr_t>(action));
}

void HyperionCall::EnsureVisible(Line line) {
	Call(Message::EnsureVisible, line);
}

void HyperionCall::SetAutomaticFold(Hyperion::AutomaticFold automaticFold) {
	Call(Message::SetAutomaticFold, static_cast<uintptr_t>(automaticFold));
}

AutomaticFold HyperionCall::AutomaticFold() {
	return static_cast<Hyperion::AutomaticFold>(Call(Message::GetAutomaticFold));
}

void HyperionCall::SetFoldFlags(Hyperion::FoldFlag flags) {
	Call(Message::SetFoldFlags, static_cast<uintptr_t>(flags));
}

void HyperionCall::EnsureVisibleEnforcePolicy(Line line) {
	Call(Message::EnsureVisibleEnforcePolicy, line);
}

void HyperionCall::SetTabIndents(bool tabIndents) {
	Call(Message::SetTabIndents, tabIndents);
}

bool HyperionCall::TabIndents() {
	return Call(Message::GetTabIndents);
}

void HyperionCall::SetBackSpaceUnIndents(bool bsUnIndents) {
	Call(Message::SetBackSpaceUnIndents, bsUnIndents);
}

bool HyperionCall::BackSpaceUnIndents() {
	return Call(Message::GetBackSpaceUnIndents);
}

void HyperionCall::SetMouseDwellTime(int periodMilliseconds) {
	Call(Message::SetMouseDwellTime, periodMilliseconds);
}

int HyperionCall::MouseDwellTime() {
	return static_cast<int>(Call(Message::GetMouseDwellTime));
}

Position HyperionCall::WordStartPosition(Position pos, bool onlyWordCharacters) {
	return Call(Message::WordStartPosition, pos, onlyWordCharacters);
}

Position HyperionCall::WordEndPosition(Position pos, bool onlyWordCharacters) {
	return Call(Message::WordEndPosition, pos, onlyWordCharacters);
}

bool HyperionCall::IsRangeWord(Position start, Position end) {
	return Call(Message::IsRangeWord, start, end);
}

void HyperionCall::SetIdleStyling(Hyperion::IdleStyling idleStyling) {
	Call(Message::SetIdleStyling, static_cast<uintptr_t>(idleStyling));
}

IdleStyling HyperionCall::IdleStyling() {
	return static_cast<Hyperion::IdleStyling>(Call(Message::GetIdleStyling));
}

void HyperionCall::SetWrapMode(Hyperion::Wrap wrapMode) {
	Call(Message::SetWrapMode, static_cast<uintptr_t>(wrapMode));
}

Wrap HyperionCall::WrapMode() {
	return static_cast<Hyperion::Wrap>(Call(Message::GetWrapMode));
}

void HyperionCall::SetWrapVisualFlags(Hyperion::WrapVisualFlag wrapVisualFlags) {
	Call(Message::SetWrapVisualFlags, static_cast<uintptr_t>(wrapVisualFlags));
}

WrapVisualFlag HyperionCall::WrapVisualFlags() {
	return static_cast<Hyperion::WrapVisualFlag>(Call(Message::GetWrapVisualFlags));
}

void HyperionCall::SetWrapVisualFlagsLocation(Hyperion::WrapVisualLocation wrapVisualFlagsLocation) {
	Call(Message::SetWrapVisualFlagsLocation, static_cast<uintptr_t>(wrapVisualFlagsLocation));
}

WrapVisualLocation HyperionCall::WrapVisualFlagsLocation() {
	return static_cast<Hyperion::WrapVisualLocation>(Call(Message::GetWrapVisualFlagsLocation));
}

void HyperionCall::SetWrapStartIndent(int indent) {
	Call(Message::SetWrapStartIndent, indent);
}

int HyperionCall::WrapStartIndent() {
	return static_cast<int>(Call(Message::GetWrapStartIndent));
}

void HyperionCall::SetWrapIndentMode(Hyperion::WrapIndentMode wrapIndentMode) {
	Call(Message::SetWrapIndentMode, static_cast<uintptr_t>(wrapIndentMode));
}

WrapIndentMode HyperionCall::WrapIndentMode() {
	return static_cast<Hyperion::WrapIndentMode>(Call(Message::GetWrapIndentMode));
}

void HyperionCall::SetLayoutCache(Hyperion::LineCache cacheMode) {
	Call(Message::SetLayoutCache, static_cast<uintptr_t>(cacheMode));
}

LineCache HyperionCall::LayoutCache() {
	return static_cast<Hyperion::LineCache>(Call(Message::GetLayoutCache));
}

void HyperionCall::SetScrollWidth(int pixelWidth) {
	Call(Message::SetScrollWidth, pixelWidth);
}

int HyperionCall::ScrollWidth() {
	return static_cast<int>(Call(Message::GetScrollWidth));
}

void HyperionCall::SetScrollWidthTracking(bool tracking) {
	Call(Message::SetScrollWidthTracking, tracking);
}

bool HyperionCall::ScrollWidthTracking() {
	return Call(Message::GetScrollWidthTracking);
}

int HyperionCall::TextWidth(int style, const char *text) {
	return static_cast<int>(CallString(Message::TextWidth, style, text));
}

void HyperionCall::SetEndAtLastLine(bool endAtLastLine) {
	Call(Message::SetEndAtLastLine, endAtLastLine);
}

bool HyperionCall::EndAtLastLine() {
	return Call(Message::GetEndAtLastLine);
}

int HyperionCall::TextHeight(Line line) {
	return static_cast<int>(Call(Message::TextHeight, line));
}

void HyperionCall::SetVScrollBar(bool visible) {
	Call(Message::SetVScrollBar, visible);
}

bool HyperionCall::VScrollBar() {
	return Call(Message::GetVScrollBar);
}

void HyperionCall::AppendText(Position length, const char *text) {
	CallString(Message::AppendText, length, text);
}

PhasesDraw HyperionCall::PhasesDraw() {
	return static_cast<Hyperion::PhasesDraw>(Call(Message::GetPhasesDraw));
}

void HyperionCall::SetPhasesDraw(Hyperion::PhasesDraw phases) {
	Call(Message::SetPhasesDraw, static_cast<uintptr_t>(phases));
}

void HyperionCall::SetFontQuality(Hyperion::FontQuality fontQuality) {
	Call(Message::SetFontQuality, static_cast<uintptr_t>(fontQuality));
}

FontQuality HyperionCall::FontQuality() {
	return static_cast<Hyperion::FontQuality>(Call(Message::GetFontQuality));
}

void HyperionCall::SetFirstVisibleLine(Line displayLine) {
	Call(Message::SetFirstVisibleLine, displayLine);
}

void HyperionCall::SetMultiPaste(Hyperion::MultiPaste multiPaste) {
	Call(Message::SetMultiPaste, static_cast<uintptr_t>(multiPaste));
}

MultiPaste HyperionCall::MultiPaste() {
	return static_cast<Hyperion::MultiPaste>(Call(Message::GetMultiPaste));
}

int HyperionCall::Tag(int tagNumber, char *tagValue) {
	return static_cast<int>(CallPointer(Message::GetTag, tagNumber, tagValue));
}

std::string HyperionCall::Tag(int tagNumber) {
	return CallReturnString(Message::GetTag, tagNumber);
}

void HyperionCall::LinesJoin() {
	Call(Message::LinesJoin);
}

void HyperionCall::LinesSplit(int pixelWidth) {
	Call(Message::LinesSplit, pixelWidth);
}

void HyperionCall::SetFoldMarginColour(bool useSetting, Colour back) {
	Call(Message::SetFoldMarginColour, useSetting, back);
}

void HyperionCall::SetFoldMarginHiColour(bool useSetting, Colour fore) {
	Call(Message::SetFoldMarginHiColour, useSetting, fore);
}

void HyperionCall::SetAccessibility(Hyperion::Accessibility accessibility) {
	Call(Message::SetAccessibility, static_cast<uintptr_t>(accessibility));
}

Accessibility HyperionCall::Accessibility() {
	return static_cast<Hyperion::Accessibility>(Call(Message::GetAccessibility));
}

void HyperionCall::LineDown() {
	Call(Message::LineDown);
}

void HyperionCall::LineDownExtend() {
	Call(Message::LineDownExtend);
}

void HyperionCall::LineUp() {
	Call(Message::LineUp);
}

void HyperionCall::LineUpExtend() {
	Call(Message::LineUpExtend);
}

void HyperionCall::CharLeft() {
	Call(Message::CharLeft);
}

void HyperionCall::CharLeftExtend() {
	Call(Message::CharLeftExtend);
}

void HyperionCall::CharRight() {
	Call(Message::CharRight);
}

void HyperionCall::CharRightExtend() {
	Call(Message::CharRightExtend);
}

void HyperionCall::WordLeft() {
	Call(Message::WordLeft);
}

void HyperionCall::WordLeftExtend() {
	Call(Message::WordLeftExtend);
}

void HyperionCall::WordRight() {
	Call(Message::WordRight);
}

void HyperionCall::WordRightExtend() {
	Call(Message::WordRightExtend);
}

void HyperionCall::Home() {
	Call(Message::Home);
}

void HyperionCall::HomeExtend() {
	Call(Message::HomeExtend);
}

void HyperionCall::LineEnd() {
	Call(Message::LineEnd);
}

void HyperionCall::LineEndExtend() {
	Call(Message::LineEndExtend);
}

void HyperionCall::DocumentStart() {
	Call(Message::DocumentStart);
}

void HyperionCall::DocumentStartExtend() {
	Call(Message::DocumentStartExtend);
}

void HyperionCall::DocumentEnd() {
	Call(Message::DocumentEnd);
}

void HyperionCall::DocumentEndExtend() {
	Call(Message::DocumentEndExtend);
}

void HyperionCall::PageUp() {
	Call(Message::PageUp);
}

void HyperionCall::PageUpExtend() {
	Call(Message::PageUpExtend);
}

void HyperionCall::PageDown() {
	Call(Message::PageDown);
}

void HyperionCall::PageDownExtend() {
	Call(Message::PageDownExtend);
}

void HyperionCall::EditToggleOvertype() {
	Call(Message::EditToggleOvertype);
}

void HyperionCall::Cancel() {
	Call(Message::Cancel);
}

void HyperionCall::DeleteBack() {
	Call(Message::DeleteBack);
}

void HyperionCall::Tab() {
	Call(Message::Tab);
}

void HyperionCall::LineIndent() {
	Call(Message::LineIndent);
}

void HyperionCall::BackTab() {
	Call(Message::BackTab);
}

void HyperionCall::LineDedent() {
	Call(Message::LineDedent);
}

void HyperionCall::NewLine() {
	Call(Message::NewLine);
}

void HyperionCall::FormFeed() {
	Call(Message::FormFeed);
}

void HyperionCall::VCHome() {
	Call(Message::VCHome);
}

void HyperionCall::VCHomeExtend() {
	Call(Message::VCHomeExtend);
}

void HyperionCall::ZoomIn() {
	Call(Message::ZoomIn);
}

void HyperionCall::ZoomOut() {
	Call(Message::ZoomOut);
}

void HyperionCall::DelWordLeft() {
	Call(Message::DelWordLeft);
}

void HyperionCall::DelWordRight() {
	Call(Message::DelWordRight);
}

void HyperionCall::DelWordRightEnd() {
	Call(Message::DelWordRightEnd);
}

void HyperionCall::LineCut() {
	Call(Message::LineCut);
}

void HyperionCall::LineDelete() {
	Call(Message::LineDelete);
}

void HyperionCall::LineTranspose() {
	Call(Message::LineTranspose);
}

void HyperionCall::LineReverse() {
	Call(Message::LineReverse);
}

void HyperionCall::LineDuplicate() {
	Call(Message::LineDuplicate);
}

void HyperionCall::LowerCase() {
	Call(Message::LowerCase);
}

void HyperionCall::UpperCase() {
	Call(Message::UpperCase);
}

void HyperionCall::LineScrollDown() {
	Call(Message::LineScrollDown);
}

void HyperionCall::LineScrollUp() {
	Call(Message::LineScrollUp);
}

void HyperionCall::DeleteBackNotLine() {
	Call(Message::DeleteBackNotLine);
}

void HyperionCall::HomeDisplay() {
	Call(Message::HomeDisplay);
}

void HyperionCall::HomeDisplayExtend() {
	Call(Message::HomeDisplayExtend);
}

void HyperionCall::LineEndDisplay() {
	Call(Message::LineEndDisplay);
}

void HyperionCall::LineEndDisplayExtend() {
	Call(Message::LineEndDisplayExtend);
}

void HyperionCall::HomeWrap() {
	Call(Message::HomeWrap);
}

void HyperionCall::HomeWrapExtend() {
	Call(Message::HomeWrapExtend);
}

void HyperionCall::LineEndWrap() {
	Call(Message::LineEndWrap);
}

void HyperionCall::LineEndWrapExtend() {
	Call(Message::LineEndWrapExtend);
}

void HyperionCall::VCHomeWrap() {
	Call(Message::VCHomeWrap);
}

void HyperionCall::VCHomeWrapExtend() {
	Call(Message::VCHomeWrapExtend);
}

void HyperionCall::LineCopy() {
	Call(Message::LineCopy);
}

void HyperionCall::MoveCaretInsideView() {
	Call(Message::MoveCaretInsideView);
}

Position HyperionCall::LineLength(Line line) {
	return Call(Message::LineLength, line);
}

void HyperionCall::BraceHighlight(Position posA, Position posB) {
	Call(Message::BraceHighlight, posA, posB);
}

void HyperionCall::BraceHighlightIndicator(bool useSetting, int indicator) {
	Call(Message::BraceHighlightIndicator, useSetting, indicator);
}

void HyperionCall::BraceBadLight(Position pos) {
	Call(Message::BraceBadLight, pos);
}

void HyperionCall::BraceBadLightIndicator(bool useSetting, int indicator) {
	Call(Message::BraceBadLightIndicator, useSetting, indicator);
}

Position HyperionCall::BraceMatch(Position pos, int maxReStyle) {
	return Call(Message::BraceMatch, pos, maxReStyle);
}

Position HyperionCall::BraceMatchNext(Position pos, Position startPos) {
	return Call(Message::BraceMatchNext, pos, startPos);
}

bool HyperionCall::ViewEOL() {
	return Call(Message::GetViewEOL);
}

void HyperionCall::SetViewEOL(bool visible) {
	Call(Message::SetViewEOL, visible);
}

IDocumentEditable *HyperionCall::DocPointer() {
	return reinterpret_cast<IDocumentEditable *>(Call(Message::GetDocPointer));
}

void HyperionCall::SetDocPointer(IDocumentEditable *doc) {
	CallPointer(Message::SetDocPointer, 0, doc);
}

void HyperionCall::SetModEventMask(Hyperion::ModificationFlags eventMask) {
	Call(Message::SetModEventMask, static_cast<uintptr_t>(eventMask));
}

Position HyperionCall::EdgeColumn() {
	return Call(Message::GetEdgeColumn);
}

void HyperionCall::SetEdgeColumn(Position column) {
	Call(Message::SetEdgeColumn, column);
}

EdgeVisualStyle HyperionCall::EdgeMode() {
	return static_cast<Hyperion::EdgeVisualStyle>(Call(Message::GetEdgeMode));
}

void HyperionCall::SetEdgeMode(Hyperion::EdgeVisualStyle edgeMode) {
	Call(Message::SetEdgeMode, static_cast<uintptr_t>(edgeMode));
}

Colour HyperionCall::EdgeColour() {
	return static_cast<Colour>(Call(Message::GetEdgeColour));
}

void HyperionCall::SetEdgeColour(Colour edgeColour) {
	Call(Message::SetEdgeColour, edgeColour);
}

void HyperionCall::MultiEdgeAddLine(Position column, Colour edgeColour) {
	Call(Message::MultiEdgeAddLine, column, edgeColour);
}

void HyperionCall::MultiEdgeClearAll() {
	Call(Message::MultiEdgeClearAll);
}

Position HyperionCall::MultiEdgeColumn(int which) {
	return Call(Message::GetMultiEdgeColumn, which);
}

void HyperionCall::SearchAnchor() {
	Call(Message::SearchAnchor);
}

Position HyperionCall::SearchNext(Hyperion::FindOption searchFlags, const char *text) {
	return CallString(Message::SearchNext, static_cast<uintptr_t>(searchFlags), text);
}

Position HyperionCall::SearchPrev(Hyperion::FindOption searchFlags, const char *text) {
	return CallString(Message::SearchPrev, static_cast<uintptr_t>(searchFlags), text);
}

Line HyperionCall::LinesOnScreen() {
	return Call(Message::LinesOnScreen);
}

void HyperionCall::UsePopUp(Hyperion::PopUp popUpMode) {
	Call(Message::UsePopUp, static_cast<uintptr_t>(popUpMode));
}

bool HyperionCall::SelectionIsRectangle() {
	return Call(Message::SelectionIsRectangle);
}

void HyperionCall::SetZoom(int zoomInPoints) {
	Call(Message::SetZoom, zoomInPoints);
}

int HyperionCall::Zoom() {
	return static_cast<int>(Call(Message::GetZoom));
}

IDocumentEditable *HyperionCall::CreateDocument(Position bytes, Hyperion::DocumentOption documentOptions) {
	return reinterpret_cast<IDocumentEditable *>(Call(Message::CreateDocument, bytes, static_cast<intptr_t>(documentOptions)));
}

void HyperionCall::AddRefDocument(IDocumentEditable *doc) {
	CallPointer(Message::AddRefDocument, 0, doc);
}

void HyperionCall::ReleaseDocument(IDocumentEditable *doc) {
	CallPointer(Message::ReleaseDocument, 0, doc);
}

DocumentOption HyperionCall::DocumentOptions() {
	return static_cast<Hyperion::DocumentOption>(Call(Message::GetDocumentOptions));
}

ModificationFlags HyperionCall::ModEventMask() {
	return static_cast<Hyperion::ModificationFlags>(Call(Message::GetModEventMask));
}

void HyperionCall::SetCommandEvents(bool commandEvents) {
	Call(Message::SetCommandEvents, commandEvents);
}

bool HyperionCall::CommandEvents() {
	return Call(Message::GetCommandEvents);
}

void HyperionCall::SetFocus(bool focus) {
	Call(Message::SetFocus, focus);
}

bool HyperionCall::Focus() {
	return Call(Message::GetFocus);
}

void HyperionCall::SetStatus(Hyperion::Status status) {
	Call(Message::SetStatus, static_cast<uintptr_t>(status));
}

Status HyperionCall::Status() {
	return static_cast<Hyperion::Status>(Call(Message::GetStatus));
}

void HyperionCall::SetMouseDownCaptures(bool captures) {
	Call(Message::SetMouseDownCaptures, captures);
}

bool HyperionCall::MouseDownCaptures() {
	return Call(Message::GetMouseDownCaptures);
}

void HyperionCall::SetMouseWheelCaptures(bool captures) {
	Call(Message::SetMouseWheelCaptures, captures);
}

bool HyperionCall::MouseWheelCaptures() {
	return Call(Message::GetMouseWheelCaptures);
}

void HyperionCall::SetCursor(Hyperion::CursorShape cursorType) {
	Call(Message::SetCursor, static_cast<uintptr_t>(cursorType));
}

CursorShape HyperionCall::Cursor() {
	return static_cast<Hyperion::CursorShape>(Call(Message::GetCursor));
}

void HyperionCall::SetControlCharSymbol(int symbol) {
	Call(Message::SetControlCharSymbol, symbol);
}

int HyperionCall::ControlCharSymbol() {
	return static_cast<int>(Call(Message::GetControlCharSymbol));
}

void HyperionCall::WordPartLeft() {
	Call(Message::WordPartLeft);
}

void HyperionCall::WordPartLeftExtend() {
	Call(Message::WordPartLeftExtend);
}

void HyperionCall::WordPartRight() {
	Call(Message::WordPartRight);
}

void HyperionCall::WordPartRightExtend() {
	Call(Message::WordPartRightExtend);
}

void HyperionCall::SetVisiblePolicy(Hyperion::VisiblePolicy visiblePolicy, int visibleSlop) {
	Call(Message::SetVisiblePolicy, static_cast<uintptr_t>(visiblePolicy), visibleSlop);
}

void HyperionCall::DelLineLeft() {
	Call(Message::DelLineLeft);
}

void HyperionCall::DelLineRight() {
	Call(Message::DelLineRight);
}

void HyperionCall::SetXOffset(int xOffset) {
	Call(Message::SetXOffset, xOffset);
}

int HyperionCall::XOffset() {
	return static_cast<int>(Call(Message::GetXOffset));
}

void HyperionCall::ChooseCaretX() {
	Call(Message::ChooseCaretX);
}

void HyperionCall::GrabFocus() {
	Call(Message::GrabFocus);
}

void HyperionCall::SetXCaretPolicy(Hyperion::CaretPolicy caretPolicy, int caretSlop) {
	Call(Message::SetXCaretPolicy, static_cast<uintptr_t>(caretPolicy), caretSlop);
}

void HyperionCall::SetYCaretPolicy(Hyperion::CaretPolicy caretPolicy, int caretSlop) {
	Call(Message::SetYCaretPolicy, static_cast<uintptr_t>(caretPolicy), caretSlop);
}

void HyperionCall::SetPrintWrapMode(Hyperion::Wrap wrapMode) {
	Call(Message::SetPrintWrapMode, static_cast<uintptr_t>(wrapMode));
}

Wrap HyperionCall::PrintWrapMode() {
	return static_cast<Hyperion::Wrap>(Call(Message::GetPrintWrapMode));
}

void HyperionCall::SetHotspotActiveFore(bool useSetting, Colour fore) {
	Call(Message::SetHotspotActiveFore, useSetting, fore);
}

Colour HyperionCall::HotspotActiveFore() {
	return static_cast<Colour>(Call(Message::GetHotspotActiveFore));
}

void HyperionCall::SetHotspotActiveBack(bool useSetting, Colour back) {
	Call(Message::SetHotspotActiveBack, useSetting, back);
}

Colour HyperionCall::HotspotActiveBack() {
	return static_cast<Colour>(Call(Message::GetHotspotActiveBack));
}

void HyperionCall::SetHotspotActiveUnderline(bool underline) {
	Call(Message::SetHotspotActiveUnderline, underline);
}

bool HyperionCall::HotspotActiveUnderline() {
	return Call(Message::GetHotspotActiveUnderline);
}

void HyperionCall::SetHotspotSingleLine(bool singleLine) {
	Call(Message::SetHotspotSingleLine, singleLine);
}

bool HyperionCall::HotspotSingleLine() {
	return Call(Message::GetHotspotSingleLine);
}

void HyperionCall::ParaDown() {
	Call(Message::ParaDown);
}

void HyperionCall::ParaDownExtend() {
	Call(Message::ParaDownExtend);
}

void HyperionCall::ParaUp() {
	Call(Message::ParaUp);
}

void HyperionCall::ParaUpExtend() {
	Call(Message::ParaUpExtend);
}

Position HyperionCall::PositionBefore(Position pos) {
	return Call(Message::PositionBefore, pos);
}

Position HyperionCall::PositionAfter(Position pos) {
	return Call(Message::PositionAfter, pos);
}

Position HyperionCall::PositionRelative(Position pos, Position relative) {
	return Call(Message::PositionRelative, pos, relative);
}

Position HyperionCall::PositionRelativeCodeUnits(Position pos, Position relative) {
	return Call(Message::PositionRelativeCodeUnits, pos, relative);
}

void HyperionCall::CopyRange(Position start, Position end) {
	Call(Message::CopyRange, start, end);
}

void HyperionCall::CopyText(Position length, const char *text) {
	CallString(Message::CopyText, length, text);
}

void HyperionCall::SetSelectionMode(Hyperion::SelectionMode selectionMode) {
	Call(Message::SetSelectionMode, static_cast<uintptr_t>(selectionMode));
}

void HyperionCall::ChangeSelectionMode(Hyperion::SelectionMode selectionMode) {
	Call(Message::ChangeSelectionMode, static_cast<uintptr_t>(selectionMode));
}

SelectionMode HyperionCall::SelectionMode() {
	return static_cast<Hyperion::SelectionMode>(Call(Message::GetSelectionMode));
}

void HyperionCall::SetMoveExtendsSelection(bool moveExtendsSelection) {
	Call(Message::SetMoveExtendsSelection, moveExtendsSelection);
}

bool HyperionCall::MoveExtendsSelection() {
	return Call(Message::GetMoveExtendsSelection);
}

Position HyperionCall::GetLineSelStartPosition(Line line) {
	return Call(Message::GetLineSelStartPosition, line);
}

Position HyperionCall::GetLineSelEndPosition(Line line) {
	return Call(Message::GetLineSelEndPosition, line);
}

void HyperionCall::LineDownRectExtend() {
	Call(Message::LineDownRectExtend);
}

void HyperionCall::LineUpRectExtend() {
	Call(Message::LineUpRectExtend);
}

void HyperionCall::CharLeftRectExtend() {
	Call(Message::CharLeftRectExtend);
}

void HyperionCall::CharRightRectExtend() {
	Call(Message::CharRightRectExtend);
}

void HyperionCall::HomeRectExtend() {
	Call(Message::HomeRectExtend);
}

void HyperionCall::VCHomeRectExtend() {
	Call(Message::VCHomeRectExtend);
}

void HyperionCall::LineEndRectExtend() {
	Call(Message::LineEndRectExtend);
}

void HyperionCall::PageUpRectExtend() {
	Call(Message::PageUpRectExtend);
}

void HyperionCall::PageDownRectExtend() {
	Call(Message::PageDownRectExtend);
}

void HyperionCall::StutteredPageUp() {
	Call(Message::StutteredPageUp);
}

void HyperionCall::StutteredPageUpExtend() {
	Call(Message::StutteredPageUpExtend);
}

void HyperionCall::StutteredPageDown() {
	Call(Message::StutteredPageDown);
}

void HyperionCall::StutteredPageDownExtend() {
	Call(Message::StutteredPageDownExtend);
}

void HyperionCall::WordLeftEnd() {
	Call(Message::WordLeftEnd);
}

void HyperionCall::WordLeftEndExtend() {
	Call(Message::WordLeftEndExtend);
}

void HyperionCall::WordRightEnd() {
	Call(Message::WordRightEnd);
}

void HyperionCall::WordRightEndExtend() {
	Call(Message::WordRightEndExtend);
}

void HyperionCall::SetWhitespaceChars(const char *characters) {
	CallString(Message::SetWhitespaceChars, 0, characters);
}

int HyperionCall::WhitespaceChars(char *characters) {
	return static_cast<int>(CallPointer(Message::GetWhitespaceChars, 0, characters));
}

std::string HyperionCall::WhitespaceChars() {
	return CallReturnString(Message::GetWhitespaceChars, 0);
}

void HyperionCall::SetPunctuationChars(const char *characters) {
	CallString(Message::SetPunctuationChars, 0, characters);
}

int HyperionCall::PunctuationChars(char *characters) {
	return static_cast<int>(CallPointer(Message::GetPunctuationChars, 0, characters));
}

std::string HyperionCall::PunctuationChars() {
	return CallReturnString(Message::GetPunctuationChars, 0);
}

void HyperionCall::SetCharsDefault() {
	Call(Message::SetCharsDefault);
}

int HyperionCall::AutoCGetCurrent() {
	return static_cast<int>(Call(Message::AutoCGetCurrent));
}

int HyperionCall::AutoCGetCurrentText(char *text) {
	return static_cast<int>(CallPointer(Message::AutoCGetCurrentText, 0, text));
}

std::string HyperionCall::AutoCGetCurrentText() {
	return CallReturnString(Message::AutoCGetCurrentText, 0);
}

void HyperionCall::AutoCSetCaseInsensitiveBehaviour(Hyperion::CaseInsensitiveBehaviour behaviour) {
	Call(Message::AutoCSetCaseInsensitiveBehaviour, static_cast<uintptr_t>(behaviour));
}

CaseInsensitiveBehaviour HyperionCall::AutoCGetCaseInsensitiveBehaviour() {
	return static_cast<Hyperion::CaseInsensitiveBehaviour>(Call(Message::AutoCGetCaseInsensitiveBehaviour));
}

void HyperionCall::AutoCSetMulti(Hyperion::MultiAutoComplete multi) {
	Call(Message::AutoCSetMulti, static_cast<uintptr_t>(multi));
}

MultiAutoComplete HyperionCall::AutoCGetMulti() {
	return static_cast<Hyperion::MultiAutoComplete>(Call(Message::AutoCGetMulti));
}

void HyperionCall::AutoCSetOrder(Hyperion::Ordering order) {
	Call(Message::AutoCSetOrder, static_cast<uintptr_t>(order));
}

Ordering HyperionCall::AutoCGetOrder() {
	return static_cast<Hyperion::Ordering>(Call(Message::AutoCGetOrder));
}

void HyperionCall::Allocate(Position bytes) {
	Call(Message::Allocate, bytes);
}

Position HyperionCall::TargetAsUTF8(char *s) {
	return CallPointer(Message::TargetAsUTF8, 0, s);
}

std::string HyperionCall::TargetAsUTF8() {
	return CallReturnString(Message::TargetAsUTF8, 0);
}

void HyperionCall::SetLengthForEncode(Position bytes) {
	Call(Message::SetLengthForEncode, bytes);
}

Position HyperionCall::EncodedFromUTF8(const char *utf8, char *encoded) {
	return CallPointer(Message::EncodedFromUTF8, reinterpret_cast<uintptr_t>(utf8), encoded);
}

std::string HyperionCall::EncodedFromUTF8(const char *utf8) {
	return CallReturnString(Message::EncodedFromUTF8, reinterpret_cast<uintptr_t>(utf8));
}

Position HyperionCall::FindColumn(Line line, Position column) {
	return Call(Message::FindColumn, line, column);
}

CaretSticky HyperionCall::CaretSticky() {
	return static_cast<Hyperion::CaretSticky>(Call(Message::GetCaretSticky));
}

void HyperionCall::SetCaretSticky(Hyperion::CaretSticky useCaretStickyBehaviour) {
	Call(Message::SetCaretSticky, static_cast<uintptr_t>(useCaretStickyBehaviour));
}

void HyperionCall::ToggleCaretSticky() {
	Call(Message::ToggleCaretSticky);
}

void HyperionCall::SetPasteConvertEndings(bool convert) {
	Call(Message::SetPasteConvertEndings, convert);
}

bool HyperionCall::PasteConvertEndings() {
	return Call(Message::GetPasteConvertEndings);
}

void HyperionCall::ReplaceRectangular(Position length, const char *text) {
	CallString(Message::ReplaceRectangular, length, text);
}

void HyperionCall::SelectionDuplicate() {
	Call(Message::SelectionDuplicate);
}

void HyperionCall::SetCaretLineBackAlpha(Hyperion::Alpha alpha) {
	Call(Message::SetCaretLineBackAlpha, static_cast<uintptr_t>(alpha));
}

Alpha HyperionCall::CaretLineBackAlpha() {
	return static_cast<Hyperion::Alpha>(Call(Message::GetCaretLineBackAlpha));
}

void HyperionCall::SetCaretStyle(Hyperion::CaretStyle caretStyle) {
	Call(Message::SetCaretStyle, static_cast<uintptr_t>(caretStyle));
}

CaretStyle HyperionCall::CaretStyle() {
	return static_cast<Hyperion::CaretStyle>(Call(Message::GetCaretStyle));
}

void HyperionCall::SetIndicatorCurrent(int indicator) {
	Call(Message::SetIndicatorCurrent, indicator);
}

int HyperionCall::IndicatorCurrent() {
	return static_cast<int>(Call(Message::GetIndicatorCurrent));
}

void HyperionCall::SetIndicatorValue(int value) {
	Call(Message::SetIndicatorValue, value);
}

int HyperionCall::IndicatorValue() {
	return static_cast<int>(Call(Message::GetIndicatorValue));
}

void HyperionCall::IndicatorFillRange(Position start, Position lengthFill) {
	Call(Message::IndicatorFillRange, start, lengthFill);
}

void HyperionCall::IndicatorClearRange(Position start, Position lengthClear) {
	Call(Message::IndicatorClearRange, start, lengthClear);
}

int HyperionCall::IndicatorAllOnFor(Position pos) {
	return static_cast<int>(Call(Message::IndicatorAllOnFor, pos));
}

int HyperionCall::IndicatorValueAt(int indicator, Position pos) {
	return static_cast<int>(Call(Message::IndicatorValueAt, indicator, pos));
}

Position HyperionCall::IndicatorStart(int indicator, Position pos) {
	return Call(Message::IndicatorStart, indicator, pos);
}

Position HyperionCall::IndicatorEnd(int indicator, Position pos) {
	return Call(Message::IndicatorEnd, indicator, pos);
}

void HyperionCall::SetPositionCache(int size) {
	Call(Message::SetPositionCache, size);
}

int HyperionCall::PositionCache() {
	return static_cast<int>(Call(Message::GetPositionCache));
}

void HyperionCall::SetLayoutThreads(int threads) {
	Call(Message::SetLayoutThreads, threads);
}

int HyperionCall::LayoutThreads() {
	return static_cast<int>(Call(Message::GetLayoutThreads));
}

void HyperionCall::CopyAllowLine() {
	Call(Message::CopyAllowLine);
}

void HyperionCall::CutAllowLine() {
	Call(Message::CutAllowLine);
}

void HyperionCall::SetCopySeparator(const char *separator) {
	CallString(Message::SetCopySeparator, 0, separator);
}

int HyperionCall::CopySeparator(char *separator) {
	return static_cast<int>(CallPointer(Message::GetCopySeparator, 0, separator));
}

std::string HyperionCall::CopySeparator() {
	return CallReturnString(Message::GetCopySeparator, 0);
}

void *HyperionCall::CharacterPointer() {
	return reinterpret_cast<void *>(Call(Message::GetCharacterPointer));
}

void *HyperionCall::RangePointer(Position start, Position lengthRange) {
	return reinterpret_cast<void *>(Call(Message::GetRangePointer, start, lengthRange));
}

Position HyperionCall::GapPosition() {
	return Call(Message::GetGapPosition);
}

void HyperionCall::IndicSetAlpha(int indicator, Hyperion::Alpha alpha) {
	Call(Message::IndicSetAlpha, indicator, static_cast<intptr_t>(alpha));
}

Alpha HyperionCall::IndicGetAlpha(int indicator) {
	return static_cast<Hyperion::Alpha>(Call(Message::IndicGetAlpha, indicator));
}

void HyperionCall::IndicSetOutlineAlpha(int indicator, Hyperion::Alpha alpha) {
	Call(Message::IndicSetOutlineAlpha, indicator, static_cast<intptr_t>(alpha));
}

Alpha HyperionCall::IndicGetOutlineAlpha(int indicator) {
	return static_cast<Hyperion::Alpha>(Call(Message::IndicGetOutlineAlpha, indicator));
}

void HyperionCall::SetExtraAscent(int extraAscent) {
	Call(Message::SetExtraAscent, extraAscent);
}

int HyperionCall::ExtraAscent() {
	return static_cast<int>(Call(Message::GetExtraAscent));
}

void HyperionCall::SetExtraDescent(int extraDescent) {
	Call(Message::SetExtraDescent, extraDescent);
}

int HyperionCall::ExtraDescent() {
	return static_cast<int>(Call(Message::GetExtraDescent));
}

MarkerSymbol HyperionCall::MarkerSymbolDefined(int markerNumber) {
	return static_cast<Hyperion::MarkerSymbol>(Call(Message::MarkerSymbolDefined, markerNumber));
}

void HyperionCall::MarginSetText(Line line, const char *text) {
	CallString(Message::MarginSetText, line, text);
}

int HyperionCall::MarginGetText(Line line, char *text) {
	return static_cast<int>(CallPointer(Message::MarginGetText, line, text));
}

std::string HyperionCall::MarginGetText(Line line) {
	return CallReturnString(Message::MarginGetText, line);
}

void HyperionCall::MarginSetStyle(Line line, int style) {
	Call(Message::MarginSetStyle, line, style);
}

int HyperionCall::MarginGetStyle(Line line) {
	return static_cast<int>(Call(Message::MarginGetStyle, line));
}

void HyperionCall::MarginSetStyles(Line line, const char *styles) {
	CallString(Message::MarginSetStyles, line, styles);
}

int HyperionCall::MarginGetStyles(Line line, char *styles) {
	return static_cast<int>(CallPointer(Message::MarginGetStyles, line, styles));
}

std::string HyperionCall::MarginGetStyles(Line line) {
	return CallReturnString(Message::MarginGetStyles, line);
}

void HyperionCall::MarginTextClearAll() {
	Call(Message::MarginTextClearAll);
}

void HyperionCall::MarginSetStyleOffset(int style) {
	Call(Message::MarginSetStyleOffset, style);
}

int HyperionCall::MarginGetStyleOffset() {
	return static_cast<int>(Call(Message::MarginGetStyleOffset));
}

void HyperionCall::SetMarginOptions(Hyperion::MarginOption marginOptions) {
	Call(Message::SetMarginOptions, static_cast<uintptr_t>(marginOptions));
}

MarginOption HyperionCall::MarginOptions() {
	return static_cast<Hyperion::MarginOption>(Call(Message::GetMarginOptions));
}

void HyperionCall::AnnotationSetText(Line line, const char *text) {
	CallString(Message::AnnotationSetText, line, text);
}

int HyperionCall::AnnotationGetText(Line line, char *text) {
	return static_cast<int>(CallPointer(Message::AnnotationGetText, line, text));
}

std::string HyperionCall::AnnotationGetText(Line line) {
	return CallReturnString(Message::AnnotationGetText, line);
}

void HyperionCall::AnnotationSetStyle(Line line, int style) {
	Call(Message::AnnotationSetStyle, line, style);
}

int HyperionCall::AnnotationGetStyle(Line line) {
	return static_cast<int>(Call(Message::AnnotationGetStyle, line));
}

void HyperionCall::AnnotationSetStyles(Line line, const char *styles) {
	CallString(Message::AnnotationSetStyles, line, styles);
}

int HyperionCall::AnnotationGetStyles(Line line, char *styles) {
	return static_cast<int>(CallPointer(Message::AnnotationGetStyles, line, styles));
}

std::string HyperionCall::AnnotationGetStyles(Line line) {
	return CallReturnString(Message::AnnotationGetStyles, line);
}

int HyperionCall::AnnotationGetLines(Line line) {
	return static_cast<int>(Call(Message::AnnotationGetLines, line));
}

void HyperionCall::AnnotationClearAll() {
	Call(Message::AnnotationClearAll);
}

void HyperionCall::AnnotationSetVisible(Hyperion::AnnotationVisible visible) {
	Call(Message::AnnotationSetVisible, static_cast<uintptr_t>(visible));
}

AnnotationVisible HyperionCall::AnnotationGetVisible() {
	return static_cast<Hyperion::AnnotationVisible>(Call(Message::AnnotationGetVisible));
}

void HyperionCall::AnnotationSetStyleOffset(int style) {
	Call(Message::AnnotationSetStyleOffset, style);
}

int HyperionCall::AnnotationGetStyleOffset() {
	return static_cast<int>(Call(Message::AnnotationGetStyleOffset));
}

void HyperionCall::ReleaseAllExtendedStyles() {
	Call(Message::ReleaseAllExtendedStyles);
}

int HyperionCall::AllocateExtendedStyles(int numberStyles) {
	return static_cast<int>(Call(Message::AllocateExtendedStyles, numberStyles));
}

void HyperionCall::AddUndoAction(int token, Hyperion::UndoFlags flags) {
	Call(Message::AddUndoAction, token, static_cast<intptr_t>(flags));
}

Position HyperionCall::CharPositionFromPoint(int x, int y) {
	return Call(Message::CharPositionFromPoint, x, y);
}

Position HyperionCall::CharPositionFromPointClose(int x, int y) {
	return Call(Message::CharPositionFromPointClose, x, y);
}

void HyperionCall::SetMouseSelectionRectangularSwitch(bool mouseSelectionRectangularSwitch) {
	Call(Message::SetMouseSelectionRectangularSwitch, mouseSelectionRectangularSwitch);
}

bool HyperionCall::MouseSelectionRectangularSwitch() {
	return Call(Message::GetMouseSelectionRectangularSwitch);
}

void HyperionCall::SetMultipleSelection(bool multipleSelection) {
	Call(Message::SetMultipleSelection, multipleSelection);
}

bool HyperionCall::MultipleSelection() {
	return Call(Message::GetMultipleSelection);
}

void HyperionCall::SetAdditionalSelectionTyping(bool additionalSelectionTyping) {
	Call(Message::SetAdditionalSelectionTyping, additionalSelectionTyping);
}

bool HyperionCall::AdditionalSelectionTyping() {
	return Call(Message::GetAdditionalSelectionTyping);
}

void HyperionCall::SetAdditionalCaretsBlink(bool additionalCaretsBlink) {
	Call(Message::SetAdditionalCaretsBlink, additionalCaretsBlink);
}

bool HyperionCall::AdditionalCaretsBlink() {
	return Call(Message::GetAdditionalCaretsBlink);
}

void HyperionCall::SetAdditionalCaretsVisible(bool additionalCaretsVisible) {
	Call(Message::SetAdditionalCaretsVisible, additionalCaretsVisible);
}

bool HyperionCall::AdditionalCaretsVisible() {
	return Call(Message::GetAdditionalCaretsVisible);
}

int HyperionCall::Selections() {
	return static_cast<int>(Call(Message::GetSelections));
}

bool HyperionCall::SelectionEmpty() {
	return Call(Message::GetSelectionEmpty);
}

void HyperionCall::ClearSelections() {
	Call(Message::ClearSelections);
}

void HyperionCall::SetSelection(Position caret, Position anchor) {
	Call(Message::SetSelection, caret, anchor);
}

void HyperionCall::AddSelection(Position caret, Position anchor) {
	Call(Message::AddSelection, caret, anchor);
}

int HyperionCall::SelectionFromPoint(int x, int y) {
	return static_cast<int>(Call(Message::SelectionFromPoint, x, y));
}

void HyperionCall::DropSelectionN(int selection) {
	Call(Message::DropSelectionN, selection);
}

void HyperionCall::SetMainSelection(int selection) {
	Call(Message::SetMainSelection, selection);
}

int HyperionCall::MainSelection() {
	return static_cast<int>(Call(Message::GetMainSelection));
}

void HyperionCall::SetSelectionNCaret(int selection, Position caret) {
	Call(Message::SetSelectionNCaret, selection, caret);
}

Position HyperionCall::SelectionNCaret(int selection) {
	return Call(Message::GetSelectionNCaret, selection);
}

void HyperionCall::SetSelectionNAnchor(int selection, Position anchor) {
	Call(Message::SetSelectionNAnchor, selection, anchor);
}

Position HyperionCall::SelectionNAnchor(int selection) {
	return Call(Message::GetSelectionNAnchor, selection);
}

void HyperionCall::SetSelectionNCaretVirtualSpace(int selection, Position space) {
	Call(Message::SetSelectionNCaretVirtualSpace, selection, space);
}

Position HyperionCall::SelectionNCaretVirtualSpace(int selection) {
	return Call(Message::GetSelectionNCaretVirtualSpace, selection);
}

void HyperionCall::SetSelectionNAnchorVirtualSpace(int selection, Position space) {
	Call(Message::SetSelectionNAnchorVirtualSpace, selection, space);
}

Position HyperionCall::SelectionNAnchorVirtualSpace(int selection) {
	return Call(Message::GetSelectionNAnchorVirtualSpace, selection);
}

void HyperionCall::SetSelectionNStart(int selection, Position anchor) {
	Call(Message::SetSelectionNStart, selection, anchor);
}

Position HyperionCall::SelectionNStart(int selection) {
	return Call(Message::GetSelectionNStart, selection);
}

Position HyperionCall::SelectionNStartVirtualSpace(int selection) {
	return Call(Message::GetSelectionNStartVirtualSpace, selection);
}

void HyperionCall::SetSelectionNEnd(int selection, Position caret) {
	Call(Message::SetSelectionNEnd, selection, caret);
}

Position HyperionCall::SelectionNEndVirtualSpace(int selection) {
	return Call(Message::GetSelectionNEndVirtualSpace, selection);
}

Position HyperionCall::SelectionNEnd(int selection) {
	return Call(Message::GetSelectionNEnd, selection);
}

void HyperionCall::SetRectangularSelectionCaret(Position caret) {
	Call(Message::SetRectangularSelectionCaret, caret);
}

Position HyperionCall::RectangularSelectionCaret() {
	return Call(Message::GetRectangularSelectionCaret);
}

void HyperionCall::SetRectangularSelectionAnchor(Position anchor) {
	Call(Message::SetRectangularSelectionAnchor, anchor);
}

Position HyperionCall::RectangularSelectionAnchor() {
	return Call(Message::GetRectangularSelectionAnchor);
}

void HyperionCall::SetRectangularSelectionCaretVirtualSpace(Position space) {
	Call(Message::SetRectangularSelectionCaretVirtualSpace, space);
}

Position HyperionCall::RectangularSelectionCaretVirtualSpace() {
	return Call(Message::GetRectangularSelectionCaretVirtualSpace);
}

void HyperionCall::SetRectangularSelectionAnchorVirtualSpace(Position space) {
	Call(Message::SetRectangularSelectionAnchorVirtualSpace, space);
}

Position HyperionCall::RectangularSelectionAnchorVirtualSpace() {
	return Call(Message::GetRectangularSelectionAnchorVirtualSpace);
}

void HyperionCall::SetVirtualSpaceOptions(Hyperion::VirtualSpace virtualSpaceOptions) {
	Call(Message::SetVirtualSpaceOptions, static_cast<uintptr_t>(virtualSpaceOptions));
}

VirtualSpace HyperionCall::VirtualSpaceOptions() {
	return static_cast<Hyperion::VirtualSpace>(Call(Message::GetVirtualSpaceOptions));
}

void HyperionCall::SetRectangularSelectionModifier(int modifier) {
	Call(Message::SetRectangularSelectionModifier, modifier);
}

int HyperionCall::RectangularSelectionModifier() {
	return static_cast<int>(Call(Message::GetRectangularSelectionModifier));
}

void HyperionCall::SetAdditionalSelFore(Colour fore) {
	Call(Message::SetAdditionalSelFore, fore);
}

void HyperionCall::SetAdditionalSelBack(Colour back) {
	Call(Message::SetAdditionalSelBack, back);
}

void HyperionCall::SetAdditionalSelAlpha(Hyperion::Alpha alpha) {
	Call(Message::SetAdditionalSelAlpha, static_cast<uintptr_t>(alpha));
}

Alpha HyperionCall::AdditionalSelAlpha() {
	return static_cast<Hyperion::Alpha>(Call(Message::GetAdditionalSelAlpha));
}

void HyperionCall::SetAdditionalCaretFore(Colour fore) {
	Call(Message::SetAdditionalCaretFore, fore);
}

Colour HyperionCall::AdditionalCaretFore() {
	return static_cast<Colour>(Call(Message::GetAdditionalCaretFore));
}

void HyperionCall::RotateSelection() {
	Call(Message::RotateSelection);
}

void HyperionCall::SwapMainAnchorCaret() {
	Call(Message::SwapMainAnchorCaret);
}

void HyperionCall::MultipleSelectAddNext() {
	Call(Message::MultipleSelectAddNext);
}

void HyperionCall::MultipleSelectAddEach() {
	Call(Message::MultipleSelectAddEach);
}

int HyperionCall::ChangeLexerState(Position start, Position end) {
	return static_cast<int>(Call(Message::ChangeLexerState, start, end));
}

Line HyperionCall::ContractedFoldNext(Line lineStart) {
	return Call(Message::ContractedFoldNext, lineStart);
}

void HyperionCall::VerticalCentreCaret() {
	Call(Message::VerticalCentreCaret);
}

void HyperionCall::MoveSelectedLinesUp() {
	Call(Message::MoveSelectedLinesUp);
}

void HyperionCall::MoveSelectedLinesDown() {
	Call(Message::MoveSelectedLinesDown);
}

void HyperionCall::SetIdentifier(int identifier) {
	Call(Message::SetIdentifier, identifier);
}

int HyperionCall::Identifier() {
	return static_cast<int>(Call(Message::GetIdentifier));
}

void HyperionCall::RGBAImageSetWidth(int width) {
	Call(Message::RGBAImageSetWidth, width);
}

void HyperionCall::RGBAImageSetHeight(int height) {
	Call(Message::RGBAImageSetHeight, height);
}

void HyperionCall::RGBAImageSetScale(int scalePercent) {
	Call(Message::RGBAImageSetScale, scalePercent);
}

void HyperionCall::MarkerDefineRGBAImage(int markerNumber, const char *pixels) {
	CallString(Message::MarkerDefineRGBAImage, markerNumber, pixels);
}

void HyperionCall::RegisterRGBAImage(int type, const char *pixels) {
	CallString(Message::RegisterRGBAImage, type, pixels);
}

void HyperionCall::ScrollToStart() {
	Call(Message::ScrollToStart);
}

void HyperionCall::ScrollToEnd() {
	Call(Message::ScrollToEnd);
}

void HyperionCall::SetTechnology(Hyperion::Technology technology) {
	Call(Message::SetTechnology, static_cast<uintptr_t>(technology));
}

Technology HyperionCall::Technology() {
	return static_cast<Hyperion::Technology>(Call(Message::GetTechnology));
}

void *HyperionCall::CreateLoader(Position bytes, Hyperion::DocumentOption documentOptions) {
	return reinterpret_cast<void *>(Call(Message::CreateLoader, bytes, static_cast<intptr_t>(documentOptions)));
}

void HyperionCall::FindIndicatorShow(Position start, Position end) {
	Call(Message::FindIndicatorShow, start, end);
}

void HyperionCall::FindIndicatorFlash(Position start, Position end) {
	Call(Message::FindIndicatorFlash, start, end);
}

void HyperionCall::FindIndicatorHide() {
	Call(Message::FindIndicatorHide);
}

void HyperionCall::VCHomeDisplay() {
	Call(Message::VCHomeDisplay);
}

void HyperionCall::VCHomeDisplayExtend() {
	Call(Message::VCHomeDisplayExtend);
}

bool HyperionCall::CaretLineVisibleAlways() {
	return Call(Message::GetCaretLineVisibleAlways);
}

void HyperionCall::SetCaretLineVisibleAlways(bool alwaysVisible) {
	Call(Message::SetCaretLineVisibleAlways, alwaysVisible);
}

void HyperionCall::SetLineEndTypesAllowed(Hyperion::LineEndType lineEndBitSet) {
	Call(Message::SetLineEndTypesAllowed, static_cast<uintptr_t>(lineEndBitSet));
}

LineEndType HyperionCall::LineEndTypesAllowed() {
	return static_cast<Hyperion::LineEndType>(Call(Message::GetLineEndTypesAllowed));
}

LineEndType HyperionCall::LineEndTypesActive() {
	return static_cast<Hyperion::LineEndType>(Call(Message::GetLineEndTypesActive));
}

void HyperionCall::SetRepresentation(const char *encodedCharacter, const char *representation) {
	CallString(Message::SetRepresentation, reinterpret_cast<uintptr_t>(encodedCharacter), representation);
}

int HyperionCall::Representation(const char *encodedCharacter, char *representation) {
	return static_cast<int>(CallPointer(Message::GetRepresentation, reinterpret_cast<uintptr_t>(encodedCharacter), representation));
}

std::string HyperionCall::Representation(const char *encodedCharacter) {
	return CallReturnString(Message::GetRepresentation, reinterpret_cast<uintptr_t>(encodedCharacter));
}

void HyperionCall::ClearRepresentation(const char *encodedCharacter) {
	Call(Message::ClearRepresentation, reinterpret_cast<uintptr_t>(encodedCharacter));
}

void HyperionCall::ClearAllRepresentations() {
	Call(Message::ClearAllRepresentations);
}

void HyperionCall::SetRepresentationAppearance(const char *encodedCharacter, Hyperion::RepresentationAppearance appearance) {
	Call(Message::SetRepresentationAppearance, reinterpret_cast<uintptr_t>(encodedCharacter), static_cast<intptr_t>(appearance));
}

RepresentationAppearance HyperionCall::RepresentationAppearance(const char *encodedCharacter) {
	return static_cast<Hyperion::RepresentationAppearance>(Call(Message::GetRepresentationAppearance, reinterpret_cast<uintptr_t>(encodedCharacter)));
}

void HyperionCall::SetRepresentationColour(const char *encodedCharacter, ColourAlpha colour) {
	Call(Message::SetRepresentationColour, reinterpret_cast<uintptr_t>(encodedCharacter), colour);
}

ColourAlpha HyperionCall::RepresentationColour(const char *encodedCharacter) {
	return static_cast<ColourAlpha>(Call(Message::GetRepresentationColour, reinterpret_cast<uintptr_t>(encodedCharacter)));
}

void HyperionCall::EOLAnnotationSetText(Line line, const char *text) {
	CallString(Message::EOLAnnotationSetText, line, text);
}

int HyperionCall::EOLAnnotationGetText(Line line, char *text) {
	return static_cast<int>(CallPointer(Message::EOLAnnotationGetText, line, text));
}

std::string HyperionCall::EOLAnnotationGetText(Line line) {
	return CallReturnString(Message::EOLAnnotationGetText, line);
}

void HyperionCall::EOLAnnotationSetStyle(Line line, int style) {
	Call(Message::EOLAnnotationSetStyle, line, style);
}

int HyperionCall::EOLAnnotationGetStyle(Line line) {
	return static_cast<int>(Call(Message::EOLAnnotationGetStyle, line));
}

void HyperionCall::EOLAnnotationClearAll() {
	Call(Message::EOLAnnotationClearAll);
}

void HyperionCall::EOLAnnotationSetVisible(Hyperion::EOLAnnotationVisible visible) {
	Call(Message::EOLAnnotationSetVisible, static_cast<uintptr_t>(visible));
}

EOLAnnotationVisible HyperionCall::EOLAnnotationGetVisible() {
	return static_cast<Hyperion::EOLAnnotationVisible>(Call(Message::EOLAnnotationGetVisible));
}

void HyperionCall::EOLAnnotationSetStyleOffset(int style) {
	Call(Message::EOLAnnotationSetStyleOffset, style);
}

int HyperionCall::EOLAnnotationGetStyleOffset() {
	return static_cast<int>(Call(Message::EOLAnnotationGetStyleOffset));
}

bool HyperionCall::SupportsFeature(Hyperion::Supports feature) {
	return Call(Message::SupportsFeature, static_cast<uintptr_t>(feature));
}

LineCharacterIndexType HyperionCall::LineCharacterIndex() {
	return static_cast<Hyperion::LineCharacterIndexType>(Call(Message::GetLineCharacterIndex));
}

void HyperionCall::AllocateLineCharacterIndex(Hyperion::LineCharacterIndexType lineCharacterIndex) {
	Call(Message::AllocateLineCharacterIndex, static_cast<uintptr_t>(lineCharacterIndex));
}

void HyperionCall::ReleaseLineCharacterIndex(Hyperion::LineCharacterIndexType lineCharacterIndex) {
	Call(Message::ReleaseLineCharacterIndex, static_cast<uintptr_t>(lineCharacterIndex));
}

Line HyperionCall::LineFromIndexPosition(Position pos, Hyperion::LineCharacterIndexType lineCharacterIndex) {
	return Call(Message::LineFromIndexPosition, pos, static_cast<intptr_t>(lineCharacterIndex));
}

Position HyperionCall::IndexPositionFromLine(Line line, Hyperion::LineCharacterIndexType lineCharacterIndex) {
	return Call(Message::IndexPositionFromLine, line, static_cast<intptr_t>(lineCharacterIndex));
}

void HyperionCall::StartRecord() {
	Call(Message::StartRecord);
}

void HyperionCall::StopRecord() {
	Call(Message::StopRecord);
}

int HyperionCall::Lexer() {
	return static_cast<int>(Call(Message::GetLexer));
}

void HyperionCall::Colourise(Position start, Position end) {
	Call(Message::Colourise, start, end);
}

void HyperionCall::SetProperty(const char *key, const char *value) {
	CallString(Message::SetProperty, reinterpret_cast<uintptr_t>(key), value);
}

void HyperionCall::SetKeyWords(int keyWordSet, const char *keyWords) {
	CallString(Message::SetKeyWords, keyWordSet, keyWords);
}

int HyperionCall::Property(const char *key, char *value) {
	return static_cast<int>(CallPointer(Message::GetProperty, reinterpret_cast<uintptr_t>(key), value));
}

std::string HyperionCall::Property(const char *key) {
	return CallReturnString(Message::GetProperty, reinterpret_cast<uintptr_t>(key));
}

int HyperionCall::PropertyExpanded(const char *key, char *value) {
	return static_cast<int>(CallPointer(Message::GetPropertyExpanded, reinterpret_cast<uintptr_t>(key), value));
}

std::string HyperionCall::PropertyExpanded(const char *key) {
	return CallReturnString(Message::GetPropertyExpanded, reinterpret_cast<uintptr_t>(key));
}

int HyperionCall::PropertyInt(const char *key, int defaultValue) {
	return static_cast<int>(Call(Message::GetPropertyInt, reinterpret_cast<uintptr_t>(key), defaultValue));
}

int HyperionCall::LexerLanguage(char *language) {
	return static_cast<int>(CallPointer(Message::GetLexerLanguage, 0, language));
}

std::string HyperionCall::LexerLanguage() {
	return CallReturnString(Message::GetLexerLanguage, 0);
}

void *HyperionCall::PrivateLexerCall(int operation, void *pointer) {
	return reinterpret_cast<void *>(CallPointer(Message::PrivateLexerCall, operation, pointer));
}

int HyperionCall::PropertyNames(char *names) {
	return static_cast<int>(CallPointer(Message::PropertyNames, 0, names));
}

std::string HyperionCall::PropertyNames() {
	return CallReturnString(Message::PropertyNames, 0);
}

TypeProperty HyperionCall::PropertyType(const char *name) {
	return static_cast<Hyperion::TypeProperty>(Call(Message::PropertyType, reinterpret_cast<uintptr_t>(name)));
}

int HyperionCall::DescribeProperty(const char *name, char *description) {
	return static_cast<int>(CallPointer(Message::DescribeProperty, reinterpret_cast<uintptr_t>(name), description));
}

std::string HyperionCall::DescribeProperty(const char *name) {
	return CallReturnString(Message::DescribeProperty, reinterpret_cast<uintptr_t>(name));
}

int HyperionCall::DescribeKeyWordSets(char *descriptions) {
	return static_cast<int>(CallPointer(Message::DescribeKeyWordSets, 0, descriptions));
}

std::string HyperionCall::DescribeKeyWordSets() {
	return CallReturnString(Message::DescribeKeyWordSets, 0);
}

LineEndType HyperionCall::LineEndTypesSupported() {
	return static_cast<Hyperion::LineEndType>(Call(Message::GetLineEndTypesSupported));
}

int HyperionCall::AllocateSubStyles(int styleBase, int numberStyles) {
	return static_cast<int>(Call(Message::AllocateSubStyles, styleBase, numberStyles));
}

int HyperionCall::SubStylesStart(int styleBase) {
	return static_cast<int>(Call(Message::GetSubStylesStart, styleBase));
}

int HyperionCall::SubStylesLength(int styleBase) {
	return static_cast<int>(Call(Message::GetSubStylesLength, styleBase));
}

int HyperionCall::StyleFromSubStyle(int subStyle) {
	return static_cast<int>(Call(Message::GetStyleFromSubStyle, subStyle));
}

int HyperionCall::PrimaryStyleFromStyle(int style) {
	return static_cast<int>(Call(Message::GetPrimaryStyleFromStyle, style));
}

void HyperionCall::FreeSubStyles() {
	Call(Message::FreeSubStyles);
}

void HyperionCall::SetIdentifiers(int style, const char *identifiers) {
	CallString(Message::SetIdentifiers, style, identifiers);
}

int HyperionCall::DistanceToSecondaryStyles() {
	return static_cast<int>(Call(Message::DistanceToSecondaryStyles));
}

int HyperionCall::SubStyleBases(char *styles) {
	return static_cast<int>(CallPointer(Message::GetSubStyleBases, 0, styles));
}

std::string HyperionCall::SubStyleBases() {
	return CallReturnString(Message::GetSubStyleBases, 0);
}

int HyperionCall::NamedStyles() {
	return static_cast<int>(Call(Message::GetNamedStyles));
}

int HyperionCall::NameOfStyle(int style, char *name) {
	return static_cast<int>(CallPointer(Message::NameOfStyle, style, name));
}

std::string HyperionCall::NameOfStyle(int style) {
	return CallReturnString(Message::NameOfStyle, style);
}

int HyperionCall::TagsOfStyle(int style, char *tags) {
	return static_cast<int>(CallPointer(Message::TagsOfStyle, style, tags));
}

std::string HyperionCall::TagsOfStyle(int style) {
	return CallReturnString(Message::TagsOfStyle, style);
}

int HyperionCall::DescriptionOfStyle(int style, char *description) {
	return static_cast<int>(CallPointer(Message::DescriptionOfStyle, style, description));
}

std::string HyperionCall::DescriptionOfStyle(int style) {
	return CallReturnString(Message::DescriptionOfStyle, style);
}

void HyperionCall::SetILexer(void *ilexer) {
	CallPointer(Message::SetILexer, 0, ilexer);
}

Bidirectional HyperionCall::Bidirectional() {
	return static_cast<Hyperion::Bidirectional>(Call(Message::GetBidirectional));
}

void HyperionCall::SetBidirectional(Hyperion::Bidirectional bidirectional) {
	Call(Message::SetBidirectional, static_cast<uintptr_t>(bidirectional));
}

//--Autogenerated -- end of section automatically generated from Hyperion.iface */

}
