name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Build Typescript Library (Web Version)
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install
      
    - name: Check TypeScript types
      run: bun run check
      
    - name: Build project
      run: bun run build
      
    - name: Check for build artifacts
      run: |
        ls -la dist/
        test -f dist/webrender/index.js
        test -f dist/webrender/index.d.ts

  build-demo:
    name: Build Demo
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: Install dependencies
      run: bun install
      
    - name: Build demo with Vite
      run: bun run build:demo
      
    - name: Upload demo artifacts
      uses: actions/upload-artifact@v4
      with:
        name: demo-build
        path: dist-demo/
        retention-days: 7

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: Install dependencies
      run: bun install
      
    - name: Run security audit
      run: bun audit
      continue-on-error: true
      
    - name: Check for high severity vulnerabilities
      run: |
        if bun audit --audit-level high; then
          echo "✓ No high severity vulnerabilities found"
        else
          echo "⚠️ High severity vulnerabilities detected"
          exit 1
        fi
      continue-on-error: true

  size-check:
    name: Bundle Size Check
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: Install dependencies
      run: bun install
      
    - name: Build project
      run: bun run build
      
    - name: Check bundle sizes
      run: |
        echo "📦 Bundle Size Report"
        echo "===================="
        
        if [ -f "dist/webrender/index.js" ]; then
          SIZE=$(wc -c < dist/webrender/index.js)
          SIZE_KB=$((SIZE / 1024))
          echo "Main bundle: ${SIZE_KB}KB"
          
          if [ $SIZE_KB -gt 500 ]; then
            echo "⚠️ Warning: Main bundle is larger than 500KB"
          else
            echo "✓ Bundle size is acceptable"
          fi
        fi
        
        echo ""
        echo "Generated files:"
        find dist/ -type f \( -name "*.js" -o -name "*.d.ts" \) | while read file; do
          size=$(wc -c < "$file")
          size_kb=$((size / 1024))
          echo "  $file: ${size_kb}KB"
        done

  native-build:
    name: Native Build (C++ / Windows)
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSVC Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Configure CMake (Release)
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build with CMake
      run: cmake --build build --config Release --parallel

    - name: Upload native artifacts
      uses: actions/upload-artifact@v4
      with:
        name: hyperion-native
        path: build/Release/
        retention-days: 14
